/*
 * Copyright and related rights waived via CC0
 *
 * You should have received a copy of the CC0 legalcode along with this
 * work. If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
 */
package org_aesh.aesh;

import static org.assertj.core.api.Assertions.assertThat;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

import org.aesh.AeshRuntimeRunner;
import org.aesh.command.Command;
import org.aesh.command.CommandDefinition;
import org.aesh.command.CommandResult;
import org.aesh.command.invocation.CommandInvocation;
import org.aesh.command.option.Option;
import org.aesh.util.completer.CompleterCommand;
import org.junit.jupiter.api.Test;

public class CompleterCommandTest {
    private static final Path GENERATED_COMPLETER_FILE = Path.of("completertarget_complete.bash");

    @Test
    void generatesCompletionScriptForCommandLoadedByClassName() throws Exception {
        Files.deleteIfExists(GENERATED_COMPLETER_FILE);
        try {
            CommandResult result = AeshRuntimeRunner.builder()
                    .command(CompleterCommand.class)
                    .args(CompleterTargetCommand.class.getName())
                    .execute();

            assertThat(result).isEqualTo(CommandResult.SUCCESS);
            assertThat(GENERATED_COMPLETER_FILE).exists().isRegularFile();
            assertThat(Files.readString(GENERATED_COMPLETER_FILE, StandardCharsets.UTF_8))
                    .contains("Completion support for completertarget generated by Aesh")
                    .contains("function _complete_completertarget")
                    .contains("--message")
                    .contains("-m")
                    .contains("default-message");
        } finally {
            Files.deleteIfExists(GENERATED_COMPLETER_FILE);
        }
    }

    @CommandDefinition(name = "completertarget", description = "Command used for completion generation")
    public static class CompleterTargetCommand implements Command<CommandInvocation> {
        @Option(name = "message", shortName = 'm', defaultValue = {"default-message"})
        private String message;

        @Override
        public CommandResult execute(CommandInvocation commandInvocation) {
            return CommandResult.SUCCESS;
        }
    }
}
