/*
 * Copyright and related rights waived via CC0
 *
 * You should have received a copy of the CC0 legalcode along with this
 * work. If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
 */
plugins {
    id "org.graalvm.internal.tck"
}

String libraryVersion = tck.testedLibraryVersion.get()

dependencies {
    testImplementation "io.opentelemetry.instrumentation:opentelemetry-grpc-1.6:$libraryVersion"
    testImplementation 'org.assertj:assertj-core:3.22.0'
    testImplementation "io.opentelemetry:opentelemetry-sdk:1.65.0"
    testImplementation "com.google.protobuf:protobuf-java:3.25.8"
    testImplementation "io.grpc:grpc-api:1.84.0"
    testImplementation "io.grpc:grpc-stub:1.84.0"
    testImplementation "io.grpc:grpc-inprocess:1.84.0"
}

graalvmNative {
    agent {
        defaultMode = "conditional"
        modes {
            conditional {
                userCodeFilterPath = "user-code-filter.json"
            }
        }
    }
}
