/*
 * Copyright and related rights waived via CC0
 *
 * You should have received a copy of the CC0 legalcode along with this
 * work. If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
 */
package lombok.launch;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.net.URLClassLoader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Base64;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.Callable;
import java.util.concurrent.CyclicBarrier;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class ShadowClassLoaderTest {
    private static final String SHADOW_SUFFIX = "lombok";
    private static final String OVERRIDE_PROPERTY = "shadow.override." + SHADOW_SUFFIX;
    private static final String RESOURCE_TARGET_NAME = "sample.shadow.ResourceTarget";
    private static final String PREPENDED_ONLY_NAME = "sample.shadow.PrependedOnly";
    private static final String CONCURRENT_LOAD_TARGET_NAME = "sample.shadow.ConcurrentLoadTarget";
    private static final int CONCURRENT_THREADS = 12;
    private static final int CONCURRENT_ROUNDS = 24;

    private static final byte[] RESOURCE_TARGET_BYTES = decode("""
            yv66vgAAAEUADQoAAgADBwAEDAAFAAYBABBqYXZhL2xhbmcvT2JqZWN0AQAGPGluaXQ+AQADKClW
            BwAIAQAcc2FtcGxlL3NoYWRvdy9SZXNvdXJjZVRhcmdldAEABENvZGUBAA9MaW5lTnVtYmVyVGFi
            bGUBAApTb3VyY2VGaWxlAQATUmVzb3VyY2VUYXJnZXQuamF2YQAhAAcAAgAAAAAAAQABAAUABgAB
            AAkAAAAdAAEAAQAAAAUqtwABsQAAAAEACgAAAAYAAQAAAAIAAQALAAAAAgAM
            """);

    private static final byte[] PREPENDED_ONLY_BYTES = decode("""
            yv66vgAAAEUAEQoAAgADBwAEDAAFAAYBABBqYXZhL2xhbmcvT2JqZWN0AQAGPGluaXQ+AQADKClW
            CAAIAQAJcHJlcGVuZGVkBwAKAQAbc2FtcGxlL3NoYWRvdy9QcmVwZW5kZWRPbmx5AQAEQ29kZQEA
            D0xpbmVOdW1iZXJUYWJsZQEABXZhbHVlAQAUKClMamF2YS9sYW5nL1N0cmluZzsBAApTb3VyY2VG
            aWxlAQASUHJlcGVuZGVkT25seS5qYXZhACEACQACAAAAAAACAAEABQAGAAEACwAAAB0AAQABAAAA
            BSq3AAGxAAAAAQAMAAAABgABAAAAAgABAA0ADgABAAsAAAAbAAEAAQAAAAMSB7AAAAABAAwAAAAG
            AAEAAAAEAAEADwAAAAIAEA==
            """);

    private static final byte[] CONCURRENT_LOAD_TARGET_BYTES = decode("""
            yv66vgAAAEUCAgoAAgADBwAEDAAFAAYBABBqYXZhL2xhbmcvT2JqZWN0AQAGPGluaXQ+AQADKClW
            BwAIAQAic2FtcGxlL3NoYWRvdy9Db25jdXJyZW50TG9hZFRhcmdldAEABENvZGUBAA9MaW5lTnVt
            YmVyVGFibGUBAARtMDAwAQADKClJAQAEbTAwMQEABG0wMDIBAARtMDAzAQAEbTAwNAEABG0wMDUB
            AARtMDA2AQAEbTAwNwEABG0wMDgBAARtMDA5AQAEbTAxMAEABG0wMTEBAARtMDEyAQAEbTAxMwEA
            BG0wMTQBAARtMDE1AQAEbTAxNgEABG0wMTcBAARtMDE4AQAEbTAxOQEABG0wMjABAARtMDIxAQAE
            bTAyMgEABG0wMjMBAARtMDI0AQAEbTAyNQEABG0wMjYBAARtMDI3AQAEbTAyOAEABG0wMjkBAARt
            MDMwAQAEbTAzMQEABG0wMzIBAARtMDMzAQAEbTAzNAEABG0wMzUBAARtMDM2AQAEbTAzNwEABG0w
            MzgBAARtMDM5AQAEbTA0MAEABG0wNDEBAARtMDQyAQAEbTA0MwEABG0wNDQBAARtMDQ1AQAEbTA0
            NgEABG0wNDcBAARtMDQ4AQAEbTA0OQEABG0wNTABAARtMDUxAQAEbTA1MgEABG0wNTMBAARtMDU0
            AQAEbTA1NQEABG0wNTYBAARtMDU3AQAEbTA1OAEABG0wNTkBAARtMDYwAQAEbTA2MQEABG0wNjIB
            AARtMDYzAQAEbTA2NAEABG0wNjUBAARtMDY2AQAEbTA2NwEABG0wNjgBAARtMDY5AQAEbTA3MAEA
            BG0wNzEBAARtMDcyAQAEbTA3MwEABG0wNzQBAARtMDc1AQAEbTA3NgEABG0wNzcBAARtMDc4AQAE
            bTA3OQEABG0wODABAARtMDgxAQAEbTA4MgEABG0wODMBAARtMDg0AQAEbTA4NQEABG0wODYBAARt
            MDg3AQAEbTA4OAEABG0wODkBAARtMDkwAQAEbTA5MQEABG0wOTIBAARtMDkzAQAEbTA5NAEABG0w
            OTUBAARtMDk2AQAEbTA5NwEABG0wOTgBAARtMDk5AQAEbTEwMAEABG0xMDEBAARtMTAyAQAEbTEw
            MwEABG0xMDQBAARtMTA1AQAEbTEwNgEABG0xMDcBAARtMTA4AQAEbTEwOQEABG0xMTABAARtMTEx
            AQAEbTExMgEABG0xMTMBAARtMTE0AQAEbTExNQEABG0xMTYBAARtMTE3AQAEbTExOAEABG0xMTkB
            AARtMTIwAQAEbTEyMQEABG0xMjIBAARtMTIzAQAEbTEyNAEABG0xMjUBAARtMTI2AQAEbTEyNwEA
            BG0xMjgBAARtMTI5AQAEbTEzMAEABG0xMzEBAARtMTMyAQAEbTEzMwEABG0xMzQBAARtMTM1AQAE
            bTEzNgEABG0xMzcBAARtMTM4AQAEbTEzOQEABG0xNDABAARtMTQxAQAEbTE0MgEABG0xNDMBAARt
            MTQ0AQAEbTE0NQEABG0xNDYBAARtMTQ3AQAEbTE0OAEABG0xNDkBAARtMTUwAQAEbTE1MQEABG0x
            NTIBAARtMTUzAQAEbTE1NAEABG0xNTUBAARtMTU2AQAEbTE1NwEABG0xNTgBAARtMTU5AQAEbTE2
            MAEABG0xNjEBAARtMTYyAQAEbTE2MwEABG0xNjQBAARtMTY1AQAEbTE2NgEABG0xNjcBAARtMTY4
            AQAEbTE2OQEABG0xNzABAARtMTcxAQAEbTE3MgEABG0xNzMBAARtMTc0AQAEbTE3NQEABG0xNzYB
            AARtMTc3AQAEbTE3OAEABG0xNzkBAARtMTgwAQAEbTE4MQEABG0xODIBAARtMTgzAQAEbTE4NAEA
            BG0xODUBAARtMTg2AQAEbTE4NwEABG0xODgBAARtMTg5AQAEbTE5MAEABG0xOTEBAARtMTkyAQAE
            bTE5MwEABG0xOTQBAARtMTk1AQAEbTE5NgEABG0xOTcBAARtMTk4AQAEbTE5OQEABG0yMDABAARt
            MjAxAQAEbTIwMgEABG0yMDMBAARtMjA0AQAEbTIwNQEABG0yMDYBAARtMjA3AQAEbTIwOAEABG0y
            MDkBAARtMjEwAQAEbTIxMQEABG0yMTIBAARtMjEzAQAEbTIxNAEABG0yMTUBAARtMjE2AQAEbTIx
            NwEABG0yMTgBAARtMjE5AQAEbTIyMAEABG0yMjEBAARtMjIyAQAEbTIyMwEABG0yMjQBAARtMjI1
            AQAEbTIyNgEABG0yMjcBAARtMjI4AQAEbTIyOQEABG0yMzABAARtMjMxAQAEbTIzMgEABG0yMzMB
            AARtMjM0AQAEbTIzNQEABG0yMzYBAARtMjM3AQAEbTIzOAEABG0yMzkBAARtMjQwAQAEbTI0MQEA
            BG0yNDIBAARtMjQzAQAEbTI0NAEABG0yNDUBAARtMjQ2AQAEbTI0NwEABG0yNDgBAARtMjQ5AQAE
            bTI1MAEABG0yNTEBAARtMjUyAQAEbTI1MwEABG0yNTQBAARtMjU1AQAEbTI1NgEABG0yNTcBAARt
            MjU4AQAEbTI1OQEABG0yNjABAARtMjYxAQAEbTI2MgEABG0yNjMBAARtMjY0AQAEbTI2NQEABG0y
            NjYBAARtMjY3AQAEbTI2OAEABG0yNjkBAARtMjcwAQAEbTI3MQEABG0yNzIBAARtMjczAQAEbTI3
            NAEABG0yNzUBAARtMjc2AQAEbTI3NwEABG0yNzgBAARtMjc5AQAEbTI4MAEABG0yODEBAARtMjgy
            AQAEbTI4MwEABG0yODQBAARtMjg1AQAEbTI4NgEABG0yODcBAARtMjg4AQAEbTI4OQEABG0yOTAB
            AARtMjkxAQAEbTI5MgEABG0yOTMBAARtMjk0AQAEbTI5NQEABG0yOTYBAARtMjk3AQAEbTI5OAEA
            BG0yOTkBAARtMzAwAQAEbTMwMQEABG0zMDIBAARtMzAzAQAEbTMwNAEABG0zMDUBAARtMzA2AQAE
            bTMwNwEABG0zMDgBAARtMzA5AQAEbTMxMAEABG0zMTEBAARtMzEyAQAEbTMxMwEABG0zMTQBAARt
            MzE1AQAEbTMxNgEABG0zMTcBAARtMzE4AQAEbTMxOQEABG0zMjABAARtMzIxAQAEbTMyMgEABG0z
            MjMBAARtMzI0AQAEbTMyNQEABG0zMjYBAARtMzI3AQAEbTMyOAEABG0zMjkBAARtMzMwAQAEbTMz
            MQEABG0zMzIBAARtMzMzAQAEbTMzNAEABG0zMzUBAARtMzM2AQAEbTMzNwEABG0zMzgBAARtMzM5
            AQAEbTM0MAEABG0zNDEBAARtMzQyAQAEbTM0MwEABG0zNDQBAARtMzQ1AQAEbTM0NgEABG0zNDcB
            AARtMzQ4AQAEbTM0OQEABG0zNTABAARtMzUxAQAEbTM1MgEABG0zNTMBAARtMzU0AQAEbTM1NQEA
            BG0zNTYBAARtMzU3AQAEbTM1OAEABG0zNTkBAARtMzYwAQAEbTM2MQEABG0zNjIBAARtMzYzAQAE
            bTM2NAEABG0zNjUBAARtMzY2AQAEbTM2NwEABG0zNjgBAARtMzY5AQAEbTM3MAEABG0zNzEBAARt
            MzcyAQAEbTM3MwEABG0zNzQBAARtMzc1AQAEbTM3NgEABG0zNzcBAARtMzc4AQAEbTM3OQEABG0z
            ODABAARtMzgxAQAEbTM4MgEABG0zODMBAARtMzg0AQAEbTM4NQEABG0zODYBAARtMzg3AQAEbTM4
            OAEABG0zODkBAARtMzkwAQAEbTM5MQEABG0zOTIBAARtMzkzAQAEbTM5NAEABG0zOTUBAARtMzk2
            AQAEbTM5NwEABG0zOTgBAARtMzk5AQAEbTQwMAEABG00MDEBAARtNDAyAQAEbTQwMwEABG00MDQB
            AARtNDA1AQAEbTQwNgEABG00MDcBAARtNDA4AQAEbTQwOQEABG00MTABAARtNDExAQAEbTQxMgEA
            BG00MTMBAARtNDE0AQAEbTQxNQEABG00MTYBAARtNDE3AQAEbTQxOAEABG00MTkBAARtNDIwAQAE
            bTQyMQEABG00MjIBAARtNDIzAQAEbTQyNAEABG00MjUBAARtNDI2AQAEbTQyNwEABG00MjgBAARt
            NDI5AQAEbTQzMAEABG00MzEBAARtNDMyAQAEbTQzMwEABG00MzQBAARtNDM1AQAEbTQzNgEABG00
            MzcBAARtNDM4AQAEbTQzOQEABG00NDABAARtNDQxAQAEbTQ0MgEABG00NDMBAARtNDQ0AQAEbTQ0
            NQEABG00NDYBAARtNDQ3AQAEbTQ0OAEABG00NDkBAARtNDUwAQAEbTQ1MQEABG00NTIBAARtNDUz
            AQAEbTQ1NAEABG00NTUBAARtNDU2AQAEbTQ1NwEABG00NTgBAARtNDU5AQAEbTQ2MAEABG00NjEB
            AARtNDYyAQAEbTQ2MwEABG00NjQBAARtNDY1AQAEbTQ2NgEABG00NjcBAARtNDY4AQAEbTQ2OQEA
            BG00NzABAARtNDcxAQAEbTQ3MgEABG00NzMBAARtNDc0AQAEbTQ3NQEABG00NzYBAARtNDc3AQAE
            bTQ3OAEABG00NzkBAARtNDgwAQAEbTQ4MQEABG00ODIBAARtNDgzAQAEbTQ4NAEABG00ODUBAARt
            NDg2AQAEbTQ4NwEABG00ODgBAARtNDg5AQAEbTQ5MAEABG00OTEBAARtNDkyAQAEbTQ5MwEABG00
            OTQBAARtNDk1AQAEbTQ5NgEABG00OTcBAARtNDk4AQAEbTQ5OQEAClNvdXJjZUZpbGUBABlDb25j
            dXJyZW50TG9hZFRhcmdldC5qYXZhACEABwACAAAAAAH1AAEABQAGAAEACQAAAB0AAQABAAAABSq3
            AAGxAAAAAQAKAAAABgABAAAAAgABAAsADAABAAkAAAAaAAEAAQAAAAIDrAAAAAEACgAAAAYAAQAA
            AAMAAQANAAwAAQAJAAAAGgABAAEAAAACBKwAAAABAAoAAAAGAAEAAAAEAAEADgAMAAEACQAAABoA
            AQABAAAAAgWsAAAAAQAKAAAABgABAAAABQABAA8ADAABAAkAAAAaAAEAAQAAAAIGrAAAAAEACgAA
            AAYAAQAAAAYAAQAQAAwAAQAJAAAAGgABAAEAAAACB6wAAAABAAoAAAAGAAEAAAAHAAEAEQAMAAEA
            CQAAABoAAQABAAAAAgisAAAAAQAKAAAABgABAAAACAABABIADAABAAkAAAAbAAEAAQAAAAMQBqwA
            AAABAAoAAAAGAAEAAAAJAAEAEwAMAAEACQAAABsAAQABAAAAAxAHrAAAAAEACgAAAAYAAQAAAAoA
            AQAUAAwAAQAJAAAAGwABAAEAAAADEAisAAAAAQAKAAAABgABAAAACwABABUADAABAAkAAAAbAAEA
            AQAAAAMQCawAAAABAAoAAAAGAAEAAAAMAAEAFgAMAAEACQAAABsAAQABAAAAAxAKrAAAAAEACgAA
            AAYAAQAAAA0AAQAXAAwAAQAJAAAAGwABAAEAAAADEAusAAAAAQAKAAAABgABAAAADgABABgADAAB
            AAkAAAAbAAEAAQAAAAMQDKwAAAABAAoAAAAGAAEAAAAPAAEAGQAMAAEACQAAABsAAQABAAAAAxAN
            rAAAAAEACgAAAAYAAQAAABAAAQAaAAwAAQAJAAAAGwABAAEAAAADEA6sAAAAAQAKAAAABgABAAAA
            EQABABsADAABAAkAAAAbAAEAAQAAAAMQD6wAAAABAAoAAAAGAAEAAAASAAEAHAAMAAEACQAAABsA
            AQABAAAAAxAQrAAAAAEACgAAAAYAAQAAABMAAQAdAAwAAQAJAAAAGwABAAEAAAADEBGsAAAAAQAK
            AAAABgABAAAAFAABAB4ADAABAAkAAAAbAAEAAQAAAAMQEqwAAAABAAoAAAAGAAEAAAAVAAEAHwAM
            AAEACQAAABsAAQABAAAAAxATrAAAAAEACgAAAAYAAQAAABYAAQAgAAwAAQAJAAAAGwABAAEAAAAD
            EBSsAAAAAQAKAAAABgABAAAAFwABACEADAABAAkAAAAbAAEAAQAAAAMQFawAAAABAAoAAAAGAAEA
            AAAYAAEAIgAMAAEACQAAABsAAQABAAAAAxAWrAAAAAEACgAAAAYAAQAAABkAAQAjAAwAAQAJAAAA
            GwABAAEAAAADEBesAAAAAQAKAAAABgABAAAAGgABACQADAABAAkAAAAbAAEAAQAAAAMQGKwAAAAB
            AAoAAAAGAAEAAAAbAAEAJQAMAAEACQAAABsAAQABAAAAAxAZrAAAAAEACgAAAAYAAQAAABwAAQAm
            AAwAAQAJAAAAGwABAAEAAAADEBqsAAAAAQAKAAAABgABAAAAHQABACcADAABAAkAAAAbAAEAAQAA
            AAMQG6wAAAABAAoAAAAGAAEAAAAeAAEAKAAMAAEACQAAABsAAQABAAAAAxAcrAAAAAEACgAAAAYA
            AQAAAB8AAQApAAwAAQAJAAAAGwABAAEAAAADEB2sAAAAAQAKAAAABgABAAAAIAABACoADAABAAkA
            AAAbAAEAAQAAAAMQHqwAAAABAAoAAAAGAAEAAAAhAAEAKwAMAAEACQAAABsAAQABAAAAAxAfrAAA
            AAEACgAAAAYAAQAAACIAAQAsAAwAAQAJAAAAGwABAAEAAAADECCsAAAAAQAKAAAABgABAAAAIwAB
            AC0ADAABAAkAAAAbAAEAAQAAAAMQIawAAAABAAoAAAAGAAEAAAAkAAEALgAMAAEACQAAABsAAQAB
            AAAAAxAirAAAAAEACgAAAAYAAQAAACUAAQAvAAwAAQAJAAAAGwABAAEAAAADECOsAAAAAQAKAAAA
            BgABAAAAJgABADAADAABAAkAAAAbAAEAAQAAAAMQJKwAAAABAAoAAAAGAAEAAAAnAAEAMQAMAAEA
            CQAAABsAAQABAAAAAxAlrAAAAAEACgAAAAYAAQAAACgAAQAyAAwAAQAJAAAAGwABAAEAAAADECas
            AAAAAQAKAAAABgABAAAAKQABADMADAABAAkAAAAbAAEAAQAAAAMQJ6wAAAABAAoAAAAGAAEAAAAq
            AAEANAAMAAEACQAAABsAAQABAAAAAxAorAAAAAEACgAAAAYAAQAAACsAAQA1AAwAAQAJAAAAGwAB
            AAEAAAADECmsAAAAAQAKAAAABgABAAAALAABADYADAABAAkAAAAbAAEAAQAAAAMQKqwAAAABAAoA
            AAAGAAEAAAAtAAEANwAMAAEACQAAABsAAQABAAAAAxArrAAAAAEACgAAAAYAAQAAAC4AAQA4AAwA
            AQAJAAAAGwABAAEAAAADECysAAAAAQAKAAAABgABAAAALwABADkADAABAAkAAAAbAAEAAQAAAAMQ
            LawAAAABAAoAAAAGAAEAAAAwAAEAOgAMAAEACQAAABsAAQABAAAAAxAurAAAAAEACgAAAAYAAQAA
            ADEAAQA7AAwAAQAJAAAAGwABAAEAAAADEC+sAAAAAQAKAAAABgABAAAAMgABADwADAABAAkAAAAb
            AAEAAQAAAAMQMKwAAAABAAoAAAAGAAEAAAAzAAEAPQAMAAEACQAAABsAAQABAAAAAxAxrAAAAAEA
            CgAAAAYAAQAAADQAAQA+AAwAAQAJAAAAGwABAAEAAAADEDKsAAAAAQAKAAAABgABAAAANQABAD8A
            DAABAAkAAAAbAAEAAQAAAAMQM6wAAAABAAoAAAAGAAEAAAA2AAEAQAAMAAEACQAAABsAAQABAAAA
            AxA0rAAAAAEACgAAAAYAAQAAADcAAQBBAAwAAQAJAAAAGwABAAEAAAADEDWsAAAAAQAKAAAABgAB
            AAAAOAABAEIADAABAAkAAAAbAAEAAQAAAAMQNqwAAAABAAoAAAAGAAEAAAA5AAEAQwAMAAEACQAA
            ABsAAQABAAAAAxA3rAAAAAEACgAAAAYAAQAAADoAAQBEAAwAAQAJAAAAGwABAAEAAAADEDisAAAA
            AQAKAAAABgABAAAAOwABAEUADAABAAkAAAAbAAEAAQAAAAMQOawAAAABAAoAAAAGAAEAAAA8AAEA
            RgAMAAEACQAAABsAAQABAAAAAxA6rAAAAAEACgAAAAYAAQAAAD0AAQBHAAwAAQAJAAAAGwABAAEA
            AAADEDusAAAAAQAKAAAABgABAAAAPgABAEgADAABAAkAAAAbAAEAAQAAAAMQPKwAAAABAAoAAAAG
            AAEAAAA/AAEASQAMAAEACQAAABsAAQABAAAAAxA9rAAAAAEACgAAAAYAAQAAAEAAAQBKAAwAAQAJ
            AAAAGwABAAEAAAADED6sAAAAAQAKAAAABgABAAAAQQABAEsADAABAAkAAAAbAAEAAQAAAAMQP6wA
            AAABAAoAAAAGAAEAAABCAAEATAAMAAEACQAAABsAAQABAAAAAxBArAAAAAEACgAAAAYAAQAAAEMA
            AQBNAAwAAQAJAAAAGwABAAEAAAADEEGsAAAAAQAKAAAABgABAAAARAABAE4ADAABAAkAAAAbAAEA
            AQAAAAMQQqwAAAABAAoAAAAGAAEAAABFAAEATwAMAAEACQAAABsAAQABAAAAAxBDrAAAAAEACgAA
            AAYAAQAAAEYAAQBQAAwAAQAJAAAAGwABAAEAAAADEESsAAAAAQAKAAAABgABAAAARwABAFEADAAB
            AAkAAAAbAAEAAQAAAAMQRawAAAABAAoAAAAGAAEAAABIAAEAUgAMAAEACQAAABsAAQABAAAAAxBG
            rAAAAAEACgAAAAYAAQAAAEkAAQBTAAwAAQAJAAAAGwABAAEAAAADEEesAAAAAQAKAAAABgABAAAA
            SgABAFQADAABAAkAAAAbAAEAAQAAAAMQSKwAAAABAAoAAAAGAAEAAABLAAEAVQAMAAEACQAAABsA
            AQABAAAAAxBJrAAAAAEACgAAAAYAAQAAAEwAAQBWAAwAAQAJAAAAGwABAAEAAAADEEqsAAAAAQAK
            AAAABgABAAAATQABAFcADAABAAkAAAAbAAEAAQAAAAMQS6wAAAABAAoAAAAGAAEAAABOAAEAWAAM
            AAEACQAAABsAAQABAAAAAxBMrAAAAAEACgAAAAYAAQAAAE8AAQBZAAwAAQAJAAAAGwABAAEAAAAD
            EE2sAAAAAQAKAAAABgABAAAAUAABAFoADAABAAkAAAAbAAEAAQAAAAMQTqwAAAABAAoAAAAGAAEA
            AABRAAEAWwAMAAEACQAAABsAAQABAAAAAxBPrAAAAAEACgAAAAYAAQAAAFIAAQBcAAwAAQAJAAAA
            GwABAAEAAAADEFCsAAAAAQAKAAAABgABAAAAUwABAF0ADAABAAkAAAAbAAEAAQAAAAMQUawAAAAB
            AAoAAAAGAAEAAABUAAEAXgAMAAEACQAAABsAAQABAAAAAxBSrAAAAAEACgAAAAYAAQAAAFUAAQBf
            AAwAAQAJAAAAGwABAAEAAAADEFOsAAAAAQAKAAAABgABAAAAVgABAGAADAABAAkAAAAbAAEAAQAA
            AAMQVKwAAAABAAoAAAAGAAEAAABXAAEAYQAMAAEACQAAABsAAQABAAAAAxBVrAAAAAEACgAAAAYA
            AQAAAFgAAQBiAAwAAQAJAAAAGwABAAEAAAADEFasAAAAAQAKAAAABgABAAAAWQABAGMADAABAAkA
            AAAbAAEAAQAAAAMQV6wAAAABAAoAAAAGAAEAAABaAAEAZAAMAAEACQAAABsAAQABAAAAAxBYrAAA
            AAEACgAAAAYAAQAAAFsAAQBlAAwAAQAJAAAAGwABAAEAAAADEFmsAAAAAQAKAAAABgABAAAAXAAB
            AGYADAABAAkAAAAbAAEAAQAAAAMQWqwAAAABAAoAAAAGAAEAAABdAAEAZwAMAAEACQAAABsAAQAB
            AAAAAxBbrAAAAAEACgAAAAYAAQAAAF4AAQBoAAwAAQAJAAAAGwABAAEAAAADEFysAAAAAQAKAAAA
            BgABAAAAXwABAGkADAABAAkAAAAbAAEAAQAAAAMQXawAAAABAAoAAAAGAAEAAABgAAEAagAMAAEA
            CQAAABsAAQABAAAAAxBerAAAAAEACgAAAAYAAQAAAGEAAQBrAAwAAQAJAAAAGwABAAEAAAADEF+s
            AAAAAQAKAAAABgABAAAAYgABAGwADAABAAkAAAAbAAEAAQAAAAMQYKwAAAABAAoAAAAGAAEAAABj
            AAEAbQAMAAEACQAAABsAAQABAAAAAxBhrAAAAAEACgAAAAYAAQAAAGQAAQBuAAwAAQAJAAAAGwAB
            AAEAAAADEGKsAAAAAQAKAAAABgABAAAAZQABAG8ADAABAAkAAAAbAAEAAQAAAAMQY6wAAAABAAoA
            AAAGAAEAAABmAAEAcAAMAAEACQAAABsAAQABAAAAAxBkrAAAAAEACgAAAAYAAQAAAGcAAQBxAAwA
            AQAJAAAAGwABAAEAAAADEGWsAAAAAQAKAAAABgABAAAAaAABAHIADAABAAkAAAAbAAEAAQAAAAMQ
            ZqwAAAABAAoAAAAGAAEAAABpAAEAcwAMAAEACQAAABsAAQABAAAAAxBnrAAAAAEACgAAAAYAAQAA
            AGoAAQB0AAwAAQAJAAAAGwABAAEAAAADEGisAAAAAQAKAAAABgABAAAAawABAHUADAABAAkAAAAb
            AAEAAQAAAAMQaawAAAABAAoAAAAGAAEAAABsAAEAdgAMAAEACQAAABsAAQABAAAAAxBqrAAAAAEA
            CgAAAAYAAQAAAG0AAQB3AAwAAQAJAAAAGwABAAEAAAADEGusAAAAAQAKAAAABgABAAAAbgABAHgA
            DAABAAkAAAAbAAEAAQAAAAMQbKwAAAABAAoAAAAGAAEAAABvAAEAeQAMAAEACQAAABsAAQABAAAA
            AxBtrAAAAAEACgAAAAYAAQAAAHAAAQB6AAwAAQAJAAAAGwABAAEAAAADEG6sAAAAAQAKAAAABgAB
            AAAAcQABAHsADAABAAkAAAAbAAEAAQAAAAMQb6wAAAABAAoAAAAGAAEAAAByAAEAfAAMAAEACQAA
            ABsAAQABAAAAAxBwrAAAAAEACgAAAAYAAQAAAHMAAQB9AAwAAQAJAAAAGwABAAEAAAADEHGsAAAA
            AQAKAAAABgABAAAAdAABAH4ADAABAAkAAAAbAAEAAQAAAAMQcqwAAAABAAoAAAAGAAEAAAB1AAEA
            fwAMAAEACQAAABsAAQABAAAAAxBzrAAAAAEACgAAAAYAAQAAAHYAAQCAAAwAAQAJAAAAGwABAAEA
            AAADEHSsAAAAAQAKAAAABgABAAAAdwABAIEADAABAAkAAAAbAAEAAQAAAAMQdawAAAABAAoAAAAG
            AAEAAAB4AAEAggAMAAEACQAAABsAAQABAAAAAxB2rAAAAAEACgAAAAYAAQAAAHkAAQCDAAwAAQAJ
            AAAAGwABAAEAAAADEHesAAAAAQAKAAAABgABAAAAegABAIQADAABAAkAAAAbAAEAAQAAAAMQeKwA
            AAABAAoAAAAGAAEAAAB7AAEAhQAMAAEACQAAABsAAQABAAAAAxB5rAAAAAEACgAAAAYAAQAAAHwA
            AQCGAAwAAQAJAAAAGwABAAEAAAADEHqsAAAAAQAKAAAABgABAAAAfQABAIcADAABAAkAAAAbAAEA
            AQAAAAMQe6wAAAABAAoAAAAGAAEAAAB+AAEAiAAMAAEACQAAABsAAQABAAAAAxB8rAAAAAEACgAA
            AAYAAQAAAH8AAQCJAAwAAQAJAAAAGwABAAEAAAADEH2sAAAAAQAKAAAABgABAAAAgAABAIoADAAB
            AAkAAAAbAAEAAQAAAAMQfqwAAAABAAoAAAAGAAEAAACBAAEAiwAMAAEACQAAABsAAQABAAAAAxB/
            rAAAAAEACgAAAAYAAQAAAIIAAQCMAAwAAQAJAAAAHAABAAEAAAAEEQCArAAAAAEACgAAAAYAAQAA
            AIMAAQCNAAwAAQAJAAAAHAABAAEAAAAEEQCBrAAAAAEACgAAAAYAAQAAAIQAAQCOAAwAAQAJAAAA
            HAABAAEAAAAEEQCCrAAAAAEACgAAAAYAAQAAAIUAAQCPAAwAAQAJAAAAHAABAAEAAAAEEQCDrAAA
            AAEACgAAAAYAAQAAAIYAAQCQAAwAAQAJAAAAHAABAAEAAAAEEQCErAAAAAEACgAAAAYAAQAAAIcA
            AQCRAAwAAQAJAAAAHAABAAEAAAAEEQCFrAAAAAEACgAAAAYAAQAAAIgAAQCSAAwAAQAJAAAAHAAB
            AAEAAAAEEQCGrAAAAAEACgAAAAYAAQAAAIkAAQCTAAwAAQAJAAAAHAABAAEAAAAEEQCHrAAAAAEA
            CgAAAAYAAQAAAIoAAQCUAAwAAQAJAAAAHAABAAEAAAAEEQCIrAAAAAEACgAAAAYAAQAAAIsAAQCV
            AAwAAQAJAAAAHAABAAEAAAAEEQCJrAAAAAEACgAAAAYAAQAAAIwAAQCWAAwAAQAJAAAAHAABAAEA
            AAAEEQCKrAAAAAEACgAAAAYAAQAAAI0AAQCXAAwAAQAJAAAAHAABAAEAAAAEEQCLrAAAAAEACgAA
            AAYAAQAAAI4AAQCYAAwAAQAJAAAAHAABAAEAAAAEEQCMrAAAAAEACgAAAAYAAQAAAI8AAQCZAAwA
            AQAJAAAAHAABAAEAAAAEEQCNrAAAAAEACgAAAAYAAQAAAJAAAQCaAAwAAQAJAAAAHAABAAEAAAAE
            EQCOrAAAAAEACgAAAAYAAQAAAJEAAQCbAAwAAQAJAAAAHAABAAEAAAAEEQCPrAAAAAEACgAAAAYA
            AQAAAJIAAQCcAAwAAQAJAAAAHAABAAEAAAAEEQCQrAAAAAEACgAAAAYAAQAAAJMAAQCdAAwAAQAJ
            AAAAHAABAAEAAAAEEQCRrAAAAAEACgAAAAYAAQAAAJQAAQCeAAwAAQAJAAAAHAABAAEAAAAEEQCS
            rAAAAAEACgAAAAYAAQAAAJUAAQCfAAwAAQAJAAAAHAABAAEAAAAEEQCTrAAAAAEACgAAAAYAAQAA
            AJYAAQCgAAwAAQAJAAAAHAABAAEAAAAEEQCUrAAAAAEACgAAAAYAAQAAAJcAAQChAAwAAQAJAAAA
            HAABAAEAAAAEEQCVrAAAAAEACgAAAAYAAQAAAJgAAQCiAAwAAQAJAAAAHAABAAEAAAAEEQCWrAAA
            AAEACgAAAAYAAQAAAJkAAQCjAAwAAQAJAAAAHAABAAEAAAAEEQCXrAAAAAEACgAAAAYAAQAAAJoA
            AQCkAAwAAQAJAAAAHAABAAEAAAAEEQCYrAAAAAEACgAAAAYAAQAAAJsAAQClAAwAAQAJAAAAHAAB
            AAEAAAAEEQCZrAAAAAEACgAAAAYAAQAAAJwAAQCmAAwAAQAJAAAAHAABAAEAAAAEEQCarAAAAAEA
            CgAAAAYAAQAAAJ0AAQCnAAwAAQAJAAAAHAABAAEAAAAEEQCbrAAAAAEACgAAAAYAAQAAAJ4AAQCo
            AAwAAQAJAAAAHAABAAEAAAAEEQCcrAAAAAEACgAAAAYAAQAAAJ8AAQCpAAwAAQAJAAAAHAABAAEA
            AAAEEQCdrAAAAAEACgAAAAYAAQAAAKAAAQCqAAwAAQAJAAAAHAABAAEAAAAEEQCerAAAAAEACgAA
            AAYAAQAAAKEAAQCrAAwAAQAJAAAAHAABAAEAAAAEEQCfrAAAAAEACgAAAAYAAQAAAKIAAQCsAAwA
            AQAJAAAAHAABAAEAAAAEEQCgrAAAAAEACgAAAAYAAQAAAKMAAQCtAAwAAQAJAAAAHAABAAEAAAAE
            EQChrAAAAAEACgAAAAYAAQAAAKQAAQCuAAwAAQAJAAAAHAABAAEAAAAEEQCirAAAAAEACgAAAAYA
            AQAAAKUAAQCvAAwAAQAJAAAAHAABAAEAAAAEEQCjrAAAAAEACgAAAAYAAQAAAKYAAQCwAAwAAQAJ
            AAAAHAABAAEAAAAEEQCkrAAAAAEACgAAAAYAAQAAAKcAAQCxAAwAAQAJAAAAHAABAAEAAAAEEQCl
            rAAAAAEACgAAAAYAAQAAAKgAAQCyAAwAAQAJAAAAHAABAAEAAAAEEQCmrAAAAAEACgAAAAYAAQAA
            AKkAAQCzAAwAAQAJAAAAHAABAAEAAAAEEQCnrAAAAAEACgAAAAYAAQAAAKoAAQC0AAwAAQAJAAAA
            HAABAAEAAAAEEQCorAAAAAEACgAAAAYAAQAAAKsAAQC1AAwAAQAJAAAAHAABAAEAAAAEEQCprAAA
            AAEACgAAAAYAAQAAAKwAAQC2AAwAAQAJAAAAHAABAAEAAAAEEQCqrAAAAAEACgAAAAYAAQAAAK0A
            AQC3AAwAAQAJAAAAHAABAAEAAAAEEQCrrAAAAAEACgAAAAYAAQAAAK4AAQC4AAwAAQAJAAAAHAAB
            AAEAAAAEEQCsrAAAAAEACgAAAAYAAQAAAK8AAQC5AAwAAQAJAAAAHAABAAEAAAAEEQCtrAAAAAEA
            CgAAAAYAAQAAALAAAQC6AAwAAQAJAAAAHAABAAEAAAAEEQCurAAAAAEACgAAAAYAAQAAALEAAQC7
            AAwAAQAJAAAAHAABAAEAAAAEEQCvrAAAAAEACgAAAAYAAQAAALIAAQC8AAwAAQAJAAAAHAABAAEA
            AAAEEQCwrAAAAAEACgAAAAYAAQAAALMAAQC9AAwAAQAJAAAAHAABAAEAAAAEEQCxrAAAAAEACgAA
            AAYAAQAAALQAAQC+AAwAAQAJAAAAHAABAAEAAAAEEQCyrAAAAAEACgAAAAYAAQAAALUAAQC/AAwA
            AQAJAAAAHAABAAEAAAAEEQCzrAAAAAEACgAAAAYAAQAAALYAAQDAAAwAAQAJAAAAHAABAAEAAAAE
            EQC0rAAAAAEACgAAAAYAAQAAALcAAQDBAAwAAQAJAAAAHAABAAEAAAAEEQC1rAAAAAEACgAAAAYA
            AQAAALgAAQDCAAwAAQAJAAAAHAABAAEAAAAEEQC2rAAAAAEACgAAAAYAAQAAALkAAQDDAAwAAQAJ
            AAAAHAABAAEAAAAEEQC3rAAAAAEACgAAAAYAAQAAALoAAQDEAAwAAQAJAAAAHAABAAEAAAAEEQC4
            rAAAAAEACgAAAAYAAQAAALsAAQDFAAwAAQAJAAAAHAABAAEAAAAEEQC5rAAAAAEACgAAAAYAAQAA
            ALwAAQDGAAwAAQAJAAAAHAABAAEAAAAEEQC6rAAAAAEACgAAAAYAAQAAAL0AAQDHAAwAAQAJAAAA
            HAABAAEAAAAEEQC7rAAAAAEACgAAAAYAAQAAAL4AAQDIAAwAAQAJAAAAHAABAAEAAAAEEQC8rAAA
            AAEACgAAAAYAAQAAAL8AAQDJAAwAAQAJAAAAHAABAAEAAAAEEQC9rAAAAAEACgAAAAYAAQAAAMAA
            AQDKAAwAAQAJAAAAHAABAAEAAAAEEQC+rAAAAAEACgAAAAYAAQAAAMEAAQDLAAwAAQAJAAAAHAAB
            AAEAAAAEEQC/rAAAAAEACgAAAAYAAQAAAMIAAQDMAAwAAQAJAAAAHAABAAEAAAAEEQDArAAAAAEA
            CgAAAAYAAQAAAMMAAQDNAAwAAQAJAAAAHAABAAEAAAAEEQDBrAAAAAEACgAAAAYAAQAAAMQAAQDO
            AAwAAQAJAAAAHAABAAEAAAAEEQDCrAAAAAEACgAAAAYAAQAAAMUAAQDPAAwAAQAJAAAAHAABAAEA
            AAAEEQDDrAAAAAEACgAAAAYAAQAAAMYAAQDQAAwAAQAJAAAAHAABAAEAAAAEEQDErAAAAAEACgAA
            AAYAAQAAAMcAAQDRAAwAAQAJAAAAHAABAAEAAAAEEQDFrAAAAAEACgAAAAYAAQAAAMgAAQDSAAwA
            AQAJAAAAHAABAAEAAAAEEQDGrAAAAAEACgAAAAYAAQAAAMkAAQDTAAwAAQAJAAAAHAABAAEAAAAE
            EQDHrAAAAAEACgAAAAYAAQAAAMoAAQDUAAwAAQAJAAAAHAABAAEAAAAEEQDIrAAAAAEACgAAAAYA
            AQAAAMsAAQDVAAwAAQAJAAAAHAABAAEAAAAEEQDJrAAAAAEACgAAAAYAAQAAAMwAAQDWAAwAAQAJ
            AAAAHAABAAEAAAAEEQDKrAAAAAEACgAAAAYAAQAAAM0AAQDXAAwAAQAJAAAAHAABAAEAAAAEEQDL
            rAAAAAEACgAAAAYAAQAAAM4AAQDYAAwAAQAJAAAAHAABAAEAAAAEEQDMrAAAAAEACgAAAAYAAQAA
            AM8AAQDZAAwAAQAJAAAAHAABAAEAAAAEEQDNrAAAAAEACgAAAAYAAQAAANAAAQDaAAwAAQAJAAAA
            HAABAAEAAAAEEQDOrAAAAAEACgAAAAYAAQAAANEAAQDbAAwAAQAJAAAAHAABAAEAAAAEEQDPrAAA
            AAEACgAAAAYAAQAAANIAAQDcAAwAAQAJAAAAHAABAAEAAAAEEQDQrAAAAAEACgAAAAYAAQAAANMA
            AQDdAAwAAQAJAAAAHAABAAEAAAAEEQDRrAAAAAEACgAAAAYAAQAAANQAAQDeAAwAAQAJAAAAHAAB
            AAEAAAAEEQDSrAAAAAEACgAAAAYAAQAAANUAAQDfAAwAAQAJAAAAHAABAAEAAAAEEQDTrAAAAAEA
            CgAAAAYAAQAAANYAAQDgAAwAAQAJAAAAHAABAAEAAAAEEQDUrAAAAAEACgAAAAYAAQAAANcAAQDh
            AAwAAQAJAAAAHAABAAEAAAAEEQDVrAAAAAEACgAAAAYAAQAAANgAAQDiAAwAAQAJAAAAHAABAAEA
            AAAEEQDWrAAAAAEACgAAAAYAAQAAANkAAQDjAAwAAQAJAAAAHAABAAEAAAAEEQDXrAAAAAEACgAA
            AAYAAQAAANoAAQDkAAwAAQAJAAAAHAABAAEAAAAEEQDYrAAAAAEACgAAAAYAAQAAANsAAQDlAAwA
            AQAJAAAAHAABAAEAAAAEEQDZrAAAAAEACgAAAAYAAQAAANwAAQDmAAwAAQAJAAAAHAABAAEAAAAE
            EQDarAAAAAEACgAAAAYAAQAAAN0AAQDnAAwAAQAJAAAAHAABAAEAAAAEEQDbrAAAAAEACgAAAAYA
            AQAAAN4AAQDoAAwAAQAJAAAAHAABAAEAAAAEEQDcrAAAAAEACgAAAAYAAQAAAN8AAQDpAAwAAQAJ
            AAAAHAABAAEAAAAEEQDdrAAAAAEACgAAAAYAAQAAAOAAAQDqAAwAAQAJAAAAHAABAAEAAAAEEQDe
            rAAAAAEACgAAAAYAAQAAAOEAAQDrAAwAAQAJAAAAHAABAAEAAAAEEQDfrAAAAAEACgAAAAYAAQAA
            AOIAAQDsAAwAAQAJAAAAHAABAAEAAAAEEQDgrAAAAAEACgAAAAYAAQAAAOMAAQDtAAwAAQAJAAAA
            HAABAAEAAAAEEQDhrAAAAAEACgAAAAYAAQAAAOQAAQDuAAwAAQAJAAAAHAABAAEAAAAEEQDirAAA
            AAEACgAAAAYAAQAAAOUAAQDvAAwAAQAJAAAAHAABAAEAAAAEEQDjrAAAAAEACgAAAAYAAQAAAOYA
            AQDwAAwAAQAJAAAAHAABAAEAAAAEEQDkrAAAAAEACgAAAAYAAQAAAOcAAQDxAAwAAQAJAAAAHAAB
            AAEAAAAEEQDlrAAAAAEACgAAAAYAAQAAAOgAAQDyAAwAAQAJAAAAHAABAAEAAAAEEQDmrAAAAAEA
            CgAAAAYAAQAAAOkAAQDzAAwAAQAJAAAAHAABAAEAAAAEEQDnrAAAAAEACgAAAAYAAQAAAOoAAQD0
            AAwAAQAJAAAAHAABAAEAAAAEEQDorAAAAAEACgAAAAYAAQAAAOsAAQD1AAwAAQAJAAAAHAABAAEA
            AAAEEQDprAAAAAEACgAAAAYAAQAAAOwAAQD2AAwAAQAJAAAAHAABAAEAAAAEEQDqrAAAAAEACgAA
            AAYAAQAAAO0AAQD3AAwAAQAJAAAAHAABAAEAAAAEEQDrrAAAAAEACgAAAAYAAQAAAO4AAQD4AAwA
            AQAJAAAAHAABAAEAAAAEEQDsrAAAAAEACgAAAAYAAQAAAO8AAQD5AAwAAQAJAAAAHAABAAEAAAAE
            EQDtrAAAAAEACgAAAAYAAQAAAPAAAQD6AAwAAQAJAAAAHAABAAEAAAAEEQDurAAAAAEACgAAAAYA
            AQAAAPEAAQD7AAwAAQAJAAAAHAABAAEAAAAEEQDvrAAAAAEACgAAAAYAAQAAAPIAAQD8AAwAAQAJ
            AAAAHAABAAEAAAAEEQDwrAAAAAEACgAAAAYAAQAAAPMAAQD9AAwAAQAJAAAAHAABAAEAAAAEEQDx
            rAAAAAEACgAAAAYAAQAAAPQAAQD+AAwAAQAJAAAAHAABAAEAAAAEEQDyrAAAAAEACgAAAAYAAQAA
            APUAAQD/AAwAAQAJAAAAHAABAAEAAAAEEQDzrAAAAAEACgAAAAYAAQAAAPYAAQEAAAwAAQAJAAAA
            HAABAAEAAAAEEQD0rAAAAAEACgAAAAYAAQAAAPcAAQEBAAwAAQAJAAAAHAABAAEAAAAEEQD1rAAA
            AAEACgAAAAYAAQAAAPgAAQECAAwAAQAJAAAAHAABAAEAAAAEEQD2rAAAAAEACgAAAAYAAQAAAPkA
            AQEDAAwAAQAJAAAAHAABAAEAAAAEEQD3rAAAAAEACgAAAAYAAQAAAPoAAQEEAAwAAQAJAAAAHAAB
            AAEAAAAEEQD4rAAAAAEACgAAAAYAAQAAAPsAAQEFAAwAAQAJAAAAHAABAAEAAAAEEQD5rAAAAAEA
            CgAAAAYAAQAAAPwAAQEGAAwAAQAJAAAAHAABAAEAAAAEEQD6rAAAAAEACgAAAAYAAQAAAP0AAQEH
            AAwAAQAJAAAAHAABAAEAAAAEEQD7rAAAAAEACgAAAAYAAQAAAP4AAQEIAAwAAQAJAAAAHAABAAEA
            AAAEEQD8rAAAAAEACgAAAAYAAQAAAP8AAQEJAAwAAQAJAAAAHAABAAEAAAAEEQD9rAAAAAEACgAA
            AAYAAQAAAQAAAQEKAAwAAQAJAAAAHAABAAEAAAAEEQD+rAAAAAEACgAAAAYAAQAAAQEAAQELAAwA
            AQAJAAAAHAABAAEAAAAEEQD/rAAAAAEACgAAAAYAAQAAAQIAAQEMAAwAAQAJAAAAHAABAAEAAAAE
            EQEArAAAAAEACgAAAAYAAQAAAQMAAQENAAwAAQAJAAAAHAABAAEAAAAEEQEBrAAAAAEACgAAAAYA
            AQAAAQQAAQEOAAwAAQAJAAAAHAABAAEAAAAEEQECrAAAAAEACgAAAAYAAQAAAQUAAQEPAAwAAQAJ
            AAAAHAABAAEAAAAEEQEDrAAAAAEACgAAAAYAAQAAAQYAAQEQAAwAAQAJAAAAHAABAAEAAAAEEQEE
            rAAAAAEACgAAAAYAAQAAAQcAAQERAAwAAQAJAAAAHAABAAEAAAAEEQEFrAAAAAEACgAAAAYAAQAA
            AQgAAQESAAwAAQAJAAAAHAABAAEAAAAEEQEGrAAAAAEACgAAAAYAAQAAAQkAAQETAAwAAQAJAAAA
            HAABAAEAAAAEEQEHrAAAAAEACgAAAAYAAQAAAQoAAQEUAAwAAQAJAAAAHAABAAEAAAAEEQEIrAAA
            AAEACgAAAAYAAQAAAQsAAQEVAAwAAQAJAAAAHAABAAEAAAAEEQEJrAAAAAEACgAAAAYAAQAAAQwA
            AQEWAAwAAQAJAAAAHAABAAEAAAAEEQEKrAAAAAEACgAAAAYAAQAAAQ0AAQEXAAwAAQAJAAAAHAAB
            AAEAAAAEEQELrAAAAAEACgAAAAYAAQAAAQ4AAQEYAAwAAQAJAAAAHAABAAEAAAAEEQEMrAAAAAEA
            CgAAAAYAAQAAAQ8AAQEZAAwAAQAJAAAAHAABAAEAAAAEEQENrAAAAAEACgAAAAYAAQAAARAAAQEa
            AAwAAQAJAAAAHAABAAEAAAAEEQEOrAAAAAEACgAAAAYAAQAAAREAAQEbAAwAAQAJAAAAHAABAAEA
            AAAEEQEPrAAAAAEACgAAAAYAAQAAARIAAQEcAAwAAQAJAAAAHAABAAEAAAAEEQEQrAAAAAEACgAA
            AAYAAQAAARMAAQEdAAwAAQAJAAAAHAABAAEAAAAEEQERrAAAAAEACgAAAAYAAQAAARQAAQEeAAwA
            AQAJAAAAHAABAAEAAAAEEQESrAAAAAEACgAAAAYAAQAAARUAAQEfAAwAAQAJAAAAHAABAAEAAAAE
            EQETrAAAAAEACgAAAAYAAQAAARYAAQEgAAwAAQAJAAAAHAABAAEAAAAEEQEUrAAAAAEACgAAAAYA
            AQAAARcAAQEhAAwAAQAJAAAAHAABAAEAAAAEEQEVrAAAAAEACgAAAAYAAQAAARgAAQEiAAwAAQAJ
            AAAAHAABAAEAAAAEEQEWrAAAAAEACgAAAAYAAQAAARkAAQEjAAwAAQAJAAAAHAABAAEAAAAEEQEX
            rAAAAAEACgAAAAYAAQAAARoAAQEkAAwAAQAJAAAAHAABAAEAAAAEEQEYrAAAAAEACgAAAAYAAQAA
            ARsAAQElAAwAAQAJAAAAHAABAAEAAAAEEQEZrAAAAAEACgAAAAYAAQAAARwAAQEmAAwAAQAJAAAA
            HAABAAEAAAAEEQEarAAAAAEACgAAAAYAAQAAAR0AAQEnAAwAAQAJAAAAHAABAAEAAAAEEQEbrAAA
            AAEACgAAAAYAAQAAAR4AAQEoAAwAAQAJAAAAHAABAAEAAAAEEQEcrAAAAAEACgAAAAYAAQAAAR8A
            AQEpAAwAAQAJAAAAHAABAAEAAAAEEQEdrAAAAAEACgAAAAYAAQAAASAAAQEqAAwAAQAJAAAAHAAB
            AAEAAAAEEQEerAAAAAEACgAAAAYAAQAAASEAAQErAAwAAQAJAAAAHAABAAEAAAAEEQEfrAAAAAEA
            CgAAAAYAAQAAASIAAQEsAAwAAQAJAAAAHAABAAEAAAAEEQEgrAAAAAEACgAAAAYAAQAAASMAAQEt
            AAwAAQAJAAAAHAABAAEAAAAEEQEhrAAAAAEACgAAAAYAAQAAASQAAQEuAAwAAQAJAAAAHAABAAEA
            AAAEEQEirAAAAAEACgAAAAYAAQAAASUAAQEvAAwAAQAJAAAAHAABAAEAAAAEEQEjrAAAAAEACgAA
            AAYAAQAAASYAAQEwAAwAAQAJAAAAHAABAAEAAAAEEQEkrAAAAAEACgAAAAYAAQAAAScAAQExAAwA
            AQAJAAAAHAABAAEAAAAEEQElrAAAAAEACgAAAAYAAQAAASgAAQEyAAwAAQAJAAAAHAABAAEAAAAE
            EQEmrAAAAAEACgAAAAYAAQAAASkAAQEzAAwAAQAJAAAAHAABAAEAAAAEEQEnrAAAAAEACgAAAAYA
            AQAAASoAAQE0AAwAAQAJAAAAHAABAAEAAAAEEQEorAAAAAEACgAAAAYAAQAAASsAAQE1AAwAAQAJ
            AAAAHAABAAEAAAAEEQEprAAAAAEACgAAAAYAAQAAASwAAQE2AAwAAQAJAAAAHAABAAEAAAAEEQEq
            rAAAAAEACgAAAAYAAQAAAS0AAQE3AAwAAQAJAAAAHAABAAEAAAAEEQErrAAAAAEACgAAAAYAAQAA
            AS4AAQE4AAwAAQAJAAAAHAABAAEAAAAEEQEsrAAAAAEACgAAAAYAAQAAAS8AAQE5AAwAAQAJAAAA
            HAABAAEAAAAEEQEtrAAAAAEACgAAAAYAAQAAATAAAQE6AAwAAQAJAAAAHAABAAEAAAAEEQEurAAA
            AAEACgAAAAYAAQAAATEAAQE7AAwAAQAJAAAAHAABAAEAAAAEEQEvrAAAAAEACgAAAAYAAQAAATIA
            AQE8AAwAAQAJAAAAHAABAAEAAAAEEQEwrAAAAAEACgAAAAYAAQAAATMAAQE9AAwAAQAJAAAAHAAB
            AAEAAAAEEQExrAAAAAEACgAAAAYAAQAAATQAAQE+AAwAAQAJAAAAHAABAAEAAAAEEQEyrAAAAAEA
            CgAAAAYAAQAAATUAAQE/AAwAAQAJAAAAHAABAAEAAAAEEQEzrAAAAAEACgAAAAYAAQAAATYAAQFA
            AAwAAQAJAAAAHAABAAEAAAAEEQE0rAAAAAEACgAAAAYAAQAAATcAAQFBAAwAAQAJAAAAHAABAAEA
            AAAEEQE1rAAAAAEACgAAAAYAAQAAATgAAQFCAAwAAQAJAAAAHAABAAEAAAAEEQE2rAAAAAEACgAA
            AAYAAQAAATkAAQFDAAwAAQAJAAAAHAABAAEAAAAEEQE3rAAAAAEACgAAAAYAAQAAAToAAQFEAAwA
            AQAJAAAAHAABAAEAAAAEEQE4rAAAAAEACgAAAAYAAQAAATsAAQFFAAwAAQAJAAAAHAABAAEAAAAE
            EQE5rAAAAAEACgAAAAYAAQAAATwAAQFGAAwAAQAJAAAAHAABAAEAAAAEEQE6rAAAAAEACgAAAAYA
            AQAAAT0AAQFHAAwAAQAJAAAAHAABAAEAAAAEEQE7rAAAAAEACgAAAAYAAQAAAT4AAQFIAAwAAQAJ
            AAAAHAABAAEAAAAEEQE8rAAAAAEACgAAAAYAAQAAAT8AAQFJAAwAAQAJAAAAHAABAAEAAAAEEQE9
            rAAAAAEACgAAAAYAAQAAAUAAAQFKAAwAAQAJAAAAHAABAAEAAAAEEQE+rAAAAAEACgAAAAYAAQAA
            AUEAAQFLAAwAAQAJAAAAHAABAAEAAAAEEQE/rAAAAAEACgAAAAYAAQAAAUIAAQFMAAwAAQAJAAAA
            HAABAAEAAAAEEQFArAAAAAEACgAAAAYAAQAAAUMAAQFNAAwAAQAJAAAAHAABAAEAAAAEEQFBrAAA
            AAEACgAAAAYAAQAAAUQAAQFOAAwAAQAJAAAAHAABAAEAAAAEEQFCrAAAAAEACgAAAAYAAQAAAUUA
            AQFPAAwAAQAJAAAAHAABAAEAAAAEEQFDrAAAAAEACgAAAAYAAQAAAUYAAQFQAAwAAQAJAAAAHAAB
            AAEAAAAEEQFErAAAAAEACgAAAAYAAQAAAUcAAQFRAAwAAQAJAAAAHAABAAEAAAAEEQFFrAAAAAEA
            CgAAAAYAAQAAAUgAAQFSAAwAAQAJAAAAHAABAAEAAAAEEQFGrAAAAAEACgAAAAYAAQAAAUkAAQFT
            AAwAAQAJAAAAHAABAAEAAAAEEQFHrAAAAAEACgAAAAYAAQAAAUoAAQFUAAwAAQAJAAAAHAABAAEA
            AAAEEQFIrAAAAAEACgAAAAYAAQAAAUsAAQFVAAwAAQAJAAAAHAABAAEAAAAEEQFJrAAAAAEACgAA
            AAYAAQAAAUwAAQFWAAwAAQAJAAAAHAABAAEAAAAEEQFKrAAAAAEACgAAAAYAAQAAAU0AAQFXAAwA
            AQAJAAAAHAABAAEAAAAEEQFLrAAAAAEACgAAAAYAAQAAAU4AAQFYAAwAAQAJAAAAHAABAAEAAAAE
            EQFMrAAAAAEACgAAAAYAAQAAAU8AAQFZAAwAAQAJAAAAHAABAAEAAAAEEQFNrAAAAAEACgAAAAYA
            AQAAAVAAAQFaAAwAAQAJAAAAHAABAAEAAAAEEQFOrAAAAAEACgAAAAYAAQAAAVEAAQFbAAwAAQAJ
            AAAAHAABAAEAAAAEEQFPrAAAAAEACgAAAAYAAQAAAVIAAQFcAAwAAQAJAAAAHAABAAEAAAAEEQFQ
            rAAAAAEACgAAAAYAAQAAAVMAAQFdAAwAAQAJAAAAHAABAAEAAAAEEQFRrAAAAAEACgAAAAYAAQAA
            AVQAAQFeAAwAAQAJAAAAHAABAAEAAAAEEQFSrAAAAAEACgAAAAYAAQAAAVUAAQFfAAwAAQAJAAAA
            HAABAAEAAAAEEQFTrAAAAAEACgAAAAYAAQAAAVYAAQFgAAwAAQAJAAAAHAABAAEAAAAEEQFUrAAA
            AAEACgAAAAYAAQAAAVcAAQFhAAwAAQAJAAAAHAABAAEAAAAEEQFVrAAAAAEACgAAAAYAAQAAAVgA
            AQFiAAwAAQAJAAAAHAABAAEAAAAEEQFWrAAAAAEACgAAAAYAAQAAAVkAAQFjAAwAAQAJAAAAHAAB
            AAEAAAAEEQFXrAAAAAEACgAAAAYAAQAAAVoAAQFkAAwAAQAJAAAAHAABAAEAAAAEEQFYrAAAAAEA
            CgAAAAYAAQAAAVsAAQFlAAwAAQAJAAAAHAABAAEAAAAEEQFZrAAAAAEACgAAAAYAAQAAAVwAAQFm
            AAwAAQAJAAAAHAABAAEAAAAEEQFarAAAAAEACgAAAAYAAQAAAV0AAQFnAAwAAQAJAAAAHAABAAEA
            AAAEEQFbrAAAAAEACgAAAAYAAQAAAV4AAQFoAAwAAQAJAAAAHAABAAEAAAAEEQFcrAAAAAEACgAA
            AAYAAQAAAV8AAQFpAAwAAQAJAAAAHAABAAEAAAAEEQFdrAAAAAEACgAAAAYAAQAAAWAAAQFqAAwA
            AQAJAAAAHAABAAEAAAAEEQFerAAAAAEACgAAAAYAAQAAAWEAAQFrAAwAAQAJAAAAHAABAAEAAAAE
            EQFfrAAAAAEACgAAAAYAAQAAAWIAAQFsAAwAAQAJAAAAHAABAAEAAAAEEQFgrAAAAAEACgAAAAYA
            AQAAAWMAAQFtAAwAAQAJAAAAHAABAAEAAAAEEQFhrAAAAAEACgAAAAYAAQAAAWQAAQFuAAwAAQAJ
            AAAAHAABAAEAAAAEEQFirAAAAAEACgAAAAYAAQAAAWUAAQFvAAwAAQAJAAAAHAABAAEAAAAEEQFj
            rAAAAAEACgAAAAYAAQAAAWYAAQFwAAwAAQAJAAAAHAABAAEAAAAEEQFkrAAAAAEACgAAAAYAAQAA
            AWcAAQFxAAwAAQAJAAAAHAABAAEAAAAEEQFlrAAAAAEACgAAAAYAAQAAAWgAAQFyAAwAAQAJAAAA
            HAABAAEAAAAEEQFmrAAAAAEACgAAAAYAAQAAAWkAAQFzAAwAAQAJAAAAHAABAAEAAAAEEQFnrAAA
            AAEACgAAAAYAAQAAAWoAAQF0AAwAAQAJAAAAHAABAAEAAAAEEQForAAAAAEACgAAAAYAAQAAAWsA
            AQF1AAwAAQAJAAAAHAABAAEAAAAEEQFprAAAAAEACgAAAAYAAQAAAWwAAQF2AAwAAQAJAAAAHAAB
            AAEAAAAEEQFqrAAAAAEACgAAAAYAAQAAAW0AAQF3AAwAAQAJAAAAHAABAAEAAAAEEQFrrAAAAAEA
            CgAAAAYAAQAAAW4AAQF4AAwAAQAJAAAAHAABAAEAAAAEEQFsrAAAAAEACgAAAAYAAQAAAW8AAQF5
            AAwAAQAJAAAAHAABAAEAAAAEEQFtrAAAAAEACgAAAAYAAQAAAXAAAQF6AAwAAQAJAAAAHAABAAEA
            AAAEEQFurAAAAAEACgAAAAYAAQAAAXEAAQF7AAwAAQAJAAAAHAABAAEAAAAEEQFvrAAAAAEACgAA
            AAYAAQAAAXIAAQF8AAwAAQAJAAAAHAABAAEAAAAEEQFwrAAAAAEACgAAAAYAAQAAAXMAAQF9AAwA
            AQAJAAAAHAABAAEAAAAEEQFxrAAAAAEACgAAAAYAAQAAAXQAAQF+AAwAAQAJAAAAHAABAAEAAAAE
            EQFyrAAAAAEACgAAAAYAAQAAAXUAAQF/AAwAAQAJAAAAHAABAAEAAAAEEQFzrAAAAAEACgAAAAYA
            AQAAAXYAAQGAAAwAAQAJAAAAHAABAAEAAAAEEQF0rAAAAAEACgAAAAYAAQAAAXcAAQGBAAwAAQAJ
            AAAAHAABAAEAAAAEEQF1rAAAAAEACgAAAAYAAQAAAXgAAQGCAAwAAQAJAAAAHAABAAEAAAAEEQF2
            rAAAAAEACgAAAAYAAQAAAXkAAQGDAAwAAQAJAAAAHAABAAEAAAAEEQF3rAAAAAEACgAAAAYAAQAA
            AXoAAQGEAAwAAQAJAAAAHAABAAEAAAAEEQF4rAAAAAEACgAAAAYAAQAAAXsAAQGFAAwAAQAJAAAA
            HAABAAEAAAAEEQF5rAAAAAEACgAAAAYAAQAAAXwAAQGGAAwAAQAJAAAAHAABAAEAAAAEEQF6rAAA
            AAEACgAAAAYAAQAAAX0AAQGHAAwAAQAJAAAAHAABAAEAAAAEEQF7rAAAAAEACgAAAAYAAQAAAX4A
            AQGIAAwAAQAJAAAAHAABAAEAAAAEEQF8rAAAAAEACgAAAAYAAQAAAX8AAQGJAAwAAQAJAAAAHAAB
            AAEAAAAEEQF9rAAAAAEACgAAAAYAAQAAAYAAAQGKAAwAAQAJAAAAHAABAAEAAAAEEQF+rAAAAAEA
            CgAAAAYAAQAAAYEAAQGLAAwAAQAJAAAAHAABAAEAAAAEEQF/rAAAAAEACgAAAAYAAQAAAYIAAQGM
            AAwAAQAJAAAAHAABAAEAAAAEEQGArAAAAAEACgAAAAYAAQAAAYMAAQGNAAwAAQAJAAAAHAABAAEA
            AAAEEQGBrAAAAAEACgAAAAYAAQAAAYQAAQGOAAwAAQAJAAAAHAABAAEAAAAEEQGCrAAAAAEACgAA
            AAYAAQAAAYUAAQGPAAwAAQAJAAAAHAABAAEAAAAEEQGDrAAAAAEACgAAAAYAAQAAAYYAAQGQAAwA
            AQAJAAAAHAABAAEAAAAEEQGErAAAAAEACgAAAAYAAQAAAYcAAQGRAAwAAQAJAAAAHAABAAEAAAAE
            EQGFrAAAAAEACgAAAAYAAQAAAYgAAQGSAAwAAQAJAAAAHAABAAEAAAAEEQGGrAAAAAEACgAAAAYA
            AQAAAYkAAQGTAAwAAQAJAAAAHAABAAEAAAAEEQGHrAAAAAEACgAAAAYAAQAAAYoAAQGUAAwAAQAJ
            AAAAHAABAAEAAAAEEQGIrAAAAAEACgAAAAYAAQAAAYsAAQGVAAwAAQAJAAAAHAABAAEAAAAEEQGJ
            rAAAAAEACgAAAAYAAQAAAYwAAQGWAAwAAQAJAAAAHAABAAEAAAAEEQGKrAAAAAEACgAAAAYAAQAA
            AY0AAQGXAAwAAQAJAAAAHAABAAEAAAAEEQGLrAAAAAEACgAAAAYAAQAAAY4AAQGYAAwAAQAJAAAA
            HAABAAEAAAAEEQGMrAAAAAEACgAAAAYAAQAAAY8AAQGZAAwAAQAJAAAAHAABAAEAAAAEEQGNrAAA
            AAEACgAAAAYAAQAAAZAAAQGaAAwAAQAJAAAAHAABAAEAAAAEEQGOrAAAAAEACgAAAAYAAQAAAZEA
            AQGbAAwAAQAJAAAAHAABAAEAAAAEEQGPrAAAAAEACgAAAAYAAQAAAZIAAQGcAAwAAQAJAAAAHAAB
            AAEAAAAEEQGQrAAAAAEACgAAAAYAAQAAAZMAAQGdAAwAAQAJAAAAHAABAAEAAAAEEQGRrAAAAAEA
            CgAAAAYAAQAAAZQAAQGeAAwAAQAJAAAAHAABAAEAAAAEEQGSrAAAAAEACgAAAAYAAQAAAZUAAQGf
            AAwAAQAJAAAAHAABAAEAAAAEEQGTrAAAAAEACgAAAAYAAQAAAZYAAQGgAAwAAQAJAAAAHAABAAEA
            AAAEEQGUrAAAAAEACgAAAAYAAQAAAZcAAQGhAAwAAQAJAAAAHAABAAEAAAAEEQGVrAAAAAEACgAA
            AAYAAQAAAZgAAQGiAAwAAQAJAAAAHAABAAEAAAAEEQGWrAAAAAEACgAAAAYAAQAAAZkAAQGjAAwA
            AQAJAAAAHAABAAEAAAAEEQGXrAAAAAEACgAAAAYAAQAAAZoAAQGkAAwAAQAJAAAAHAABAAEAAAAE
            EQGYrAAAAAEACgAAAAYAAQAAAZsAAQGlAAwAAQAJAAAAHAABAAEAAAAEEQGZrAAAAAEACgAAAAYA
            AQAAAZwAAQGmAAwAAQAJAAAAHAABAAEAAAAEEQGarAAAAAEACgAAAAYAAQAAAZ0AAQGnAAwAAQAJ
            AAAAHAABAAEAAAAEEQGbrAAAAAEACgAAAAYAAQAAAZ4AAQGoAAwAAQAJAAAAHAABAAEAAAAEEQGc
            rAAAAAEACgAAAAYAAQAAAZ8AAQGpAAwAAQAJAAAAHAABAAEAAAAEEQGdrAAAAAEACgAAAAYAAQAA
            AaAAAQGqAAwAAQAJAAAAHAABAAEAAAAEEQGerAAAAAEACgAAAAYAAQAAAaEAAQGrAAwAAQAJAAAA
            HAABAAEAAAAEEQGfrAAAAAEACgAAAAYAAQAAAaIAAQGsAAwAAQAJAAAAHAABAAEAAAAEEQGgrAAA
            AAEACgAAAAYAAQAAAaMAAQGtAAwAAQAJAAAAHAABAAEAAAAEEQGhrAAAAAEACgAAAAYAAQAAAaQA
            AQGuAAwAAQAJAAAAHAABAAEAAAAEEQGirAAAAAEACgAAAAYAAQAAAaUAAQGvAAwAAQAJAAAAHAAB
            AAEAAAAEEQGjrAAAAAEACgAAAAYAAQAAAaYAAQGwAAwAAQAJAAAAHAABAAEAAAAEEQGkrAAAAAEA
            CgAAAAYAAQAAAacAAQGxAAwAAQAJAAAAHAABAAEAAAAEEQGlrAAAAAEACgAAAAYAAQAAAagAAQGy
            AAwAAQAJAAAAHAABAAEAAAAEEQGmrAAAAAEACgAAAAYAAQAAAakAAQGzAAwAAQAJAAAAHAABAAEA
            AAAEEQGnrAAAAAEACgAAAAYAAQAAAaoAAQG0AAwAAQAJAAAAHAABAAEAAAAEEQGorAAAAAEACgAA
            AAYAAQAAAasAAQG1AAwAAQAJAAAAHAABAAEAAAAEEQGprAAAAAEACgAAAAYAAQAAAawAAQG2AAwA
            AQAJAAAAHAABAAEAAAAEEQGqrAAAAAEACgAAAAYAAQAAAa0AAQG3AAwAAQAJAAAAHAABAAEAAAAE
            EQGrrAAAAAEACgAAAAYAAQAAAa4AAQG4AAwAAQAJAAAAHAABAAEAAAAEEQGsrAAAAAEACgAAAAYA
            AQAAAa8AAQG5AAwAAQAJAAAAHAABAAEAAAAEEQGtrAAAAAEACgAAAAYAAQAAAbAAAQG6AAwAAQAJ
            AAAAHAABAAEAAAAEEQGurAAAAAEACgAAAAYAAQAAAbEAAQG7AAwAAQAJAAAAHAABAAEAAAAEEQGv
            rAAAAAEACgAAAAYAAQAAAbIAAQG8AAwAAQAJAAAAHAABAAEAAAAEEQGwrAAAAAEACgAAAAYAAQAA
            AbMAAQG9AAwAAQAJAAAAHAABAAEAAAAEEQGxrAAAAAEACgAAAAYAAQAAAbQAAQG+AAwAAQAJAAAA
            HAABAAEAAAAEEQGyrAAAAAEACgAAAAYAAQAAAbUAAQG/AAwAAQAJAAAAHAABAAEAAAAEEQGzrAAA
            AAEACgAAAAYAAQAAAbYAAQHAAAwAAQAJAAAAHAABAAEAAAAEEQG0rAAAAAEACgAAAAYAAQAAAbcA
            AQHBAAwAAQAJAAAAHAABAAEAAAAEEQG1rAAAAAEACgAAAAYAAQAAAbgAAQHCAAwAAQAJAAAAHAAB
            AAEAAAAEEQG2rAAAAAEACgAAAAYAAQAAAbkAAQHDAAwAAQAJAAAAHAABAAEAAAAEEQG3rAAAAAEA
            CgAAAAYAAQAAAboAAQHEAAwAAQAJAAAAHAABAAEAAAAEEQG4rAAAAAEACgAAAAYAAQAAAbsAAQHF
            AAwAAQAJAAAAHAABAAEAAAAEEQG5rAAAAAEACgAAAAYAAQAAAbwAAQHGAAwAAQAJAAAAHAABAAEA
            AAAEEQG6rAAAAAEACgAAAAYAAQAAAb0AAQHHAAwAAQAJAAAAHAABAAEAAAAEEQG7rAAAAAEACgAA
            AAYAAQAAAb4AAQHIAAwAAQAJAAAAHAABAAEAAAAEEQG8rAAAAAEACgAAAAYAAQAAAb8AAQHJAAwA
            AQAJAAAAHAABAAEAAAAEEQG9rAAAAAEACgAAAAYAAQAAAcAAAQHKAAwAAQAJAAAAHAABAAEAAAAE
            EQG+rAAAAAEACgAAAAYAAQAAAcEAAQHLAAwAAQAJAAAAHAABAAEAAAAEEQG/rAAAAAEACgAAAAYA
            AQAAAcIAAQHMAAwAAQAJAAAAHAABAAEAAAAEEQHArAAAAAEACgAAAAYAAQAAAcMAAQHNAAwAAQAJ
            AAAAHAABAAEAAAAEEQHBrAAAAAEACgAAAAYAAQAAAcQAAQHOAAwAAQAJAAAAHAABAAEAAAAEEQHC
            rAAAAAEACgAAAAYAAQAAAcUAAQHPAAwAAQAJAAAAHAABAAEAAAAEEQHDrAAAAAEACgAAAAYAAQAA
            AcYAAQHQAAwAAQAJAAAAHAABAAEAAAAEEQHErAAAAAEACgAAAAYAAQAAAccAAQHRAAwAAQAJAAAA
            HAABAAEAAAAEEQHFrAAAAAEACgAAAAYAAQAAAcgAAQHSAAwAAQAJAAAAHAABAAEAAAAEEQHGrAAA
            AAEACgAAAAYAAQAAAckAAQHTAAwAAQAJAAAAHAABAAEAAAAEEQHHrAAAAAEACgAAAAYAAQAAAcoA
            AQHUAAwAAQAJAAAAHAABAAEAAAAEEQHIrAAAAAEACgAAAAYAAQAAAcsAAQHVAAwAAQAJAAAAHAAB
            AAEAAAAEEQHJrAAAAAEACgAAAAYAAQAAAcwAAQHWAAwAAQAJAAAAHAABAAEAAAAEEQHKrAAAAAEA
            CgAAAAYAAQAAAc0AAQHXAAwAAQAJAAAAHAABAAEAAAAEEQHLrAAAAAEACgAAAAYAAQAAAc4AAQHY
            AAwAAQAJAAAAHAABAAEAAAAEEQHMrAAAAAEACgAAAAYAAQAAAc8AAQHZAAwAAQAJAAAAHAABAAEA
            AAAEEQHNrAAAAAEACgAAAAYAAQAAAdAAAQHaAAwAAQAJAAAAHAABAAEAAAAEEQHOrAAAAAEACgAA
            AAYAAQAAAdEAAQHbAAwAAQAJAAAAHAABAAEAAAAEEQHPrAAAAAEACgAAAAYAAQAAAdIAAQHcAAwA
            AQAJAAAAHAABAAEAAAAEEQHQrAAAAAEACgAAAAYAAQAAAdMAAQHdAAwAAQAJAAAAHAABAAEAAAAE
            EQHRrAAAAAEACgAAAAYAAQAAAdQAAQHeAAwAAQAJAAAAHAABAAEAAAAEEQHSrAAAAAEACgAAAAYA
            AQAAAdUAAQHfAAwAAQAJAAAAHAABAAEAAAAEEQHTrAAAAAEACgAAAAYAAQAAAdYAAQHgAAwAAQAJ
            AAAAHAABAAEAAAAEEQHUrAAAAAEACgAAAAYAAQAAAdcAAQHhAAwAAQAJAAAAHAABAAEAAAAEEQHV
            rAAAAAEACgAAAAYAAQAAAdgAAQHiAAwAAQAJAAAAHAABAAEAAAAEEQHWrAAAAAEACgAAAAYAAQAA
            AdkAAQHjAAwAAQAJAAAAHAABAAEAAAAEEQHXrAAAAAEACgAAAAYAAQAAAdoAAQHkAAwAAQAJAAAA
            HAABAAEAAAAEEQHYrAAAAAEACgAAAAYAAQAAAdsAAQHlAAwAAQAJAAAAHAABAAEAAAAEEQHZrAAA
            AAEACgAAAAYAAQAAAdwAAQHmAAwAAQAJAAAAHAABAAEAAAAEEQHarAAAAAEACgAAAAYAAQAAAd0A
            AQHnAAwAAQAJAAAAHAABAAEAAAAEEQHbrAAAAAEACgAAAAYAAQAAAd4AAQHoAAwAAQAJAAAAHAAB
            AAEAAAAEEQHcrAAAAAEACgAAAAYAAQAAAd8AAQHpAAwAAQAJAAAAHAABAAEAAAAEEQHdrAAAAAEA
            CgAAAAYAAQAAAeAAAQHqAAwAAQAJAAAAHAABAAEAAAAEEQHerAAAAAEACgAAAAYAAQAAAeEAAQHr
            AAwAAQAJAAAAHAABAAEAAAAEEQHfrAAAAAEACgAAAAYAAQAAAeIAAQHsAAwAAQAJAAAAHAABAAEA
            AAAEEQHgrAAAAAEACgAAAAYAAQAAAeMAAQHtAAwAAQAJAAAAHAABAAEAAAAEEQHhrAAAAAEACgAA
            AAYAAQAAAeQAAQHuAAwAAQAJAAAAHAABAAEAAAAEEQHirAAAAAEACgAAAAYAAQAAAeUAAQHvAAwA
            AQAJAAAAHAABAAEAAAAEEQHjrAAAAAEACgAAAAYAAQAAAeYAAQHwAAwAAQAJAAAAHAABAAEAAAAE
            EQHkrAAAAAEACgAAAAYAAQAAAecAAQHxAAwAAQAJAAAAHAABAAEAAAAEEQHlrAAAAAEACgAAAAYA
            AQAAAegAAQHyAAwAAQAJAAAAHAABAAEAAAAEEQHmrAAAAAEACgAAAAYAAQAAAekAAQHzAAwAAQAJ
            AAAAHAABAAEAAAAEEQHnrAAAAAEACgAAAAYAAQAAAeoAAQH0AAwAAQAJAAAAHAABAAEAAAAEEQHo
            rAAAAAEACgAAAAYAAQAAAesAAQH1AAwAAQAJAAAAHAABAAEAAAAEEQHprAAAAAEACgAAAAYAAQAA
            AewAAQH2AAwAAQAJAAAAHAABAAEAAAAEEQHqrAAAAAEACgAAAAYAAQAAAe0AAQH3AAwAAQAJAAAA
            HAABAAEAAAAEEQHrrAAAAAEACgAAAAYAAQAAAe4AAQH4AAwAAQAJAAAAHAABAAEAAAAEEQHsrAAA
            AAEACgAAAAYAAQAAAe8AAQH5AAwAAQAJAAAAHAABAAEAAAAEEQHtrAAAAAEACgAAAAYAAQAAAfAA
            AQH6AAwAAQAJAAAAHAABAAEAAAAEEQHurAAAAAEACgAAAAYAAQAAAfEAAQH7AAwAAQAJAAAAHAAB
            AAEAAAAEEQHvrAAAAAEACgAAAAYAAQAAAfIAAQH8AAwAAQAJAAAAHAABAAEAAAAEEQHwrAAAAAEA
            CgAAAAYAAQAAAfMAAQH9AAwAAQAJAAAAHAABAAEAAAAEEQHxrAAAAAEACgAAAAYAAQAAAfQAAQH+
            AAwAAQAJAAAAHAABAAEAAAAEEQHyrAAAAAEACgAAAAYAAQAAAfUAAQH/AAwAAQAJAAAAHAABAAEA
            AAAEEQHzrAAAAAEACgAAAAYAAQAAAfYAAQIAAAAAAgIB
            """);

    @AfterEach
    void clearOverrideProperty() {
        System.clearProperty(OVERRIDE_PROPERTY);
    }

    @Test
    void loadsResourcesFromShadowAwareParentClasspath(@TempDir Path tempDir) throws Exception {
        Path selfBase = Files.createDirectory(tempDir.resolve("self"));
        Path parentRoot = Files.createDirectory(tempDir.resolve("parent-shadow"));
        writeShadowMarker(parentRoot);
        writeBytes(parentRoot, classResourcePath(RESOURCE_TARGET_NAME), RESOURCE_TARGET_BYTES);
        writeBytes(parentRoot, shadowResourcePath(RESOURCE_TARGET_NAME), RESOURCE_TARGET_BYTES);
        writeString(parentRoot.resolve("sample/shadow/settings.txt"), "shadow-aware");

        try (URLClassLoader parent = newUrlClassLoader(parentRoot)) {
            ShadowClassLoader shadowClassLoader = new ShadowClassLoader(parent, SHADOW_SUFFIX, selfBase.toString(), List.of(), List.of());

            URL classResource = shadowClassLoader.getResource(classResourcePath(RESOURCE_TARGET_NAME));
            URL textResource = shadowClassLoader.getResource("sample/shadow/settings.txt");
            List<String> resourceUrls = Collections.list(shadowClassLoader.getResources(classResourcePath(RESOURCE_TARGET_NAME)))
                    .stream()
                    .map(URL::toString)
                    .toList();

            assertThat(classResource).isNotNull();
            assertThat(classResource.toString()).endsWith("ResourceTarget.SCL.lombok");
            assertThat(textResource).isNotNull();
            assertThat(readString(textResource)).isEqualTo("shadow-aware");
            assertThat(resourceUrls).hasSize(2);
            assertThat(resourceUrls).anyMatch(url -> url.endsWith("ResourceTarget.class"));
            assertThat(resourceUrls).anyMatch(url -> url.endsWith("ResourceTarget.SCL.lombok"));
        }
    }

    @Test
    void skipsShadowEntriesWhenOverridesAreConfigured(@TempDir Path tempDir) throws Exception {
        Path selfBase = Files.createDirectory(tempDir.resolve("self"));
        Path overrideDir = Files.createDirectory(tempDir.resolve("override"));
        Path shadowRoot = Files.createDirectory(tempDir.resolve("parent-shadow"));
        Path plainRoot = Files.createDirectory(tempDir.resolve("parent-plain"));
        writeShadowMarker(shadowRoot);
        writeBytes(shadowRoot, shadowResourcePath(RESOURCE_TARGET_NAME), RESOURCE_TARGET_BYTES);
        writeBytes(plainRoot, shadowResourcePath(RESOURCE_TARGET_NAME), RESOURCE_TARGET_BYTES);
        System.setProperty(OVERRIDE_PROPERTY, overrideDir.toString());

        try (URLClassLoader parent = newUrlClassLoader(shadowRoot, plainRoot)) {
            ShadowClassLoader shadowClassLoader = new ShadowClassLoader(parent, SHADOW_SUFFIX, selfBase.toString(), List.of(), List.of());

            URL classResource = shadowClassLoader.getResource(classResourcePath(RESOURCE_TARGET_NAME));

            assertThat(classResource).isNotNull();
            assertThat(classResource.toString()).startsWith(plainRoot.toUri().toString());
            assertThat(classResource.toString()).endsWith("ResourceTarget.SCL.lombok");
        }
    }

    @Test
    void loadsClassesFromPrependedParents(@TempDir Path tempDir) throws Exception {
        Path selfBase = Files.createDirectory(tempDir.resolve("self"));
        Path prependedRoot = Files.createDirectory(tempDir.resolve("prepended"));
        writeBytes(prependedRoot, classResourcePath(PREPENDED_ONLY_NAME), PREPENDED_ONLY_BYTES);

        try (URLClassLoader parent = newUrlClassLoader(); URLClassLoader prependedParent = newUrlClassLoader(prependedRoot)) {
            ShadowClassLoader shadowClassLoader = new ShadowClassLoader(parent, SHADOW_SUFFIX, selfBase.toString(), List.of(), List.of());
            shadowClassLoader.prependParent(prependedParent);

            Class<?> loadedClass = shadowClassLoader.loadClass(PREPENDED_ONLY_NAME, false);

            assertThat(loadedClass.getName()).isEqualTo(PREPENDED_ONLY_NAME);
            assertThat(loadedClass.getClassLoader()).isSameAs(prependedParent);
        }
    }

    @Test
    void reusesAlreadyLoadedClassesAndHandlesConcurrentDuplicateDefinitions(@TempDir Path tempDir) throws Exception {
        Path selfBase = Files.createDirectory(tempDir.resolve("self"));
        writeBytes(selfBase, shadowResourcePath(CONCURRENT_LOAD_TARGET_NAME), CONCURRENT_LOAD_TARGET_BYTES);

        try (URLClassLoader parent = newUrlClassLoader()) {
            ShadowClassLoader shadowClassLoader = new ShadowClassLoader(parent, SHADOW_SUFFIX, selfBase.toString(), List.of(), List.of());

            Class<?> firstLoad = shadowClassLoader.loadClass(CONCURRENT_LOAD_TARGET_NAME, false);
            Class<?> secondLoad = shadowClassLoader.loadClass(CONCURRENT_LOAD_TARGET_NAME, false);

            assertThat(secondLoad).isSameAs(firstLoad);

            for (int round = 0; round < CONCURRENT_ROUNDS; round++) {
                ShadowClassLoader concurrentLoader = new ShadowClassLoader(parent, SHADOW_SUFFIX, selfBase.toString(), List.of(), List.of());
                List<Class<?>> loadedClasses = runConcurrentLoadRound(concurrentLoader, CONCURRENT_LOAD_TARGET_NAME);
                assertThat(loadedClasses).isNotEmpty();
                assertThat(loadedClasses).allMatch(candidate -> candidate.getName().equals(firstLoad.getName()));
                assertThat(loadedClasses).allSatisfy(candidate -> assertThat(candidate.getClassLoader()).isSameAs(concurrentLoader));
                assertThat(loadedClasses.stream().distinct().toList()).hasSize(1);
            }
        }
    }

    private static List<Class<?>> runConcurrentLoadRound(ShadowClassLoader shadowClassLoader, String className) throws Exception {
        ExecutorService executorService = Executors.newFixedThreadPool(CONCURRENT_THREADS);
        CyclicBarrier barrier = new CyclicBarrier(CONCURRENT_THREADS);
        List<Callable<Class<?>>> tasks = new ArrayList<>();
        for (int index = 0; index < CONCURRENT_THREADS; index++) {
            tasks.add(() -> {
                barrier.await();
                return shadowClassLoader.loadClass(className, false);
            });
        }

        try {
            List<Future<Class<?>>> futures = executorService.invokeAll(tasks);
            List<Class<?>> loadedClasses = new ArrayList<>();
            for (Future<Class<?>> future : futures) {
                loadedClasses.add(future.get(30, TimeUnit.SECONDS));
            }
            return loadedClasses;
        } finally {
            executorService.shutdownNow();
            assertThat(executorService.awaitTermination(30, TimeUnit.SECONDS)).isTrue();
        }
    }

    private static URLClassLoader newUrlClassLoader(Path... roots) throws IOException {
        URL[] urls = new URL[roots.length];
        for (int index = 0; index < roots.length; index++) {
            urls[index] = roots[index].toUri().toURL();
        }
        return new URLClassLoader(urls, null);
    }

    private static void writeShadowMarker(Path root) throws IOException {
        writeString(root.resolve("META-INF/ShadowClassLoader"), SHADOW_SUFFIX + System.lineSeparator());
    }

    private static void writeString(Path path, String value) throws IOException {
        Files.createDirectories(path.getParent());
        Files.writeString(path, value, StandardCharsets.UTF_8);
    }

    private static void writeBytes(Path root, String relativePath, byte[] bytes) throws IOException {
        Path output = root.resolve(relativePath);
        Files.createDirectories(output.getParent());
        Files.write(output, bytes);
    }

    private static String readString(URL url) throws IOException {
        try (InputStream inputStream = url.openStream()) {
            return new String(inputStream.readAllBytes(), StandardCharsets.UTF_8);
        }
    }

    private static String classResourcePath(String className) {
        return className.replace('.', '/') + ".class";
    }

    private static String shadowResourcePath(String className) {
        return className.replace('.', '/') + ".SCL." + SHADOW_SUFFIX;
    }

    private static byte[] decode(String value) {
        return Base64.getMimeDecoder().decode(value);
    }
}
