handlers = java.util.logging.ConsoleHandler
.level = INFO
org.codehaus.groovy.vmplugin.VMPluginFactory.level = FINE
java.util.logging.ConsoleHandler.level = FINE
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter
