/*
 * Copyright and related rights waived via CC0
 *
 * You should have received a copy of the CC0 legalcode along with this
 * work. If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
 */
package org_apache_groovy.groovy_xml

import groovy.namespace.QName
import groovy.util.Node
import groovy.util.NodeList
import groovy.xml.DOMBuilder
import groovy.xml.MarkupBuilder
import groovy.xml.Namespace
import groovy.xml.XmlNodePrinter
import groovy.xml.XmlParser
import groovy.xml.XmlSlurper
import groovy.xml.XmlUtil
import groovy.xml.slurpersupport.GPathResult
import org.junit.jupiter.api.Test
import org.w3c.dom.Document

import java.io.PrintWriter
import java.io.StringReader
import java.io.StringWriter

import static org.assertj.core.api.Assertions.assertThat

public class Groovy_xmlTest {
    @Test
    void xmlParserBuildsMutableNodeTreeWithNamespacesAndAttributes() {
        Namespace bookNamespace = new Namespace('urn:books', 'bk')
        QName bookName = bookNamespace.get('book')
        QName titleName = bookNamespace.get('title')
        QName authorName = bookNamespace.get('author')
        XmlParser parser = new XmlParser(false, true)

        Node catalog = parser.parseText('''
                <bk:catalog xmlns:bk="urn:books">
                  <bk:book id="b1" available="true">
                    <bk:title>Groovy in Action</bk:title>
                    <bk:author>Paul King</bk:author>
                  </bk:book>
                </bk:catalog>
                '''.stripIndent())

        assertThat(catalog.name()).isEqualTo(bookNamespace.get('catalog'))
        NodeList books = catalog.getAt(bookName)
        assertThat(books).hasSize(1)

        Node firstBook = books.get(0) as Node
        assertThat(firstBook.attributes()).containsEntry('id', 'b1')
        assertThat(firstBook.attributes()).containsEntry('available', 'true')
        assertThat(firstBook.getAt(titleName).get(0).text()).isEqualTo('Groovy in Action')

        Node secondBook = catalog.appendNode(bookName, [id: 'b2', available: 'false'])
        secondBook.appendNode(titleName, 'Native Groovy XML')
        secondBook.appendNode(authorName, 'GraalVM')

        String serialized = XmlUtil.serialize(catalog)
        assertThat(serialized).contains('catalog')
        assertThat(serialized).contains('urn:books')
        assertThat(serialized).contains('b2')
        assertThat(serialized).contains('Native Groovy XML')
    }

    @Test
    void xmlSlurperNavigatesGPathResultsWithAttributesAndIndexes() {
        XmlSlurper slurper = new XmlSlurper(false, false)
        GPathResult feed = slurper.parseText('''
                <feed>
                  <entry id="e1" category="news">
                    <title>First</title>
                    <author active="true">Ada</author>
                  </entry>
                  <entry id="e2" category="docs">
                    <title>Second</title>
                    <author active="false">Grace</author>
                  </entry>
                </feed>
                '''.stripIndent())

        GPathResult entries = feed.getProperty('entry') as GPathResult
        GPathResult firstEntry = entries.getAt(0) as GPathResult
        GPathResult secondEntry = entries.getAt(1) as GPathResult

        assertThat(entries.size()).isEqualTo(2)
        assertThat(firstEntry.getProperty('@id').toString()).isEqualTo('e1')
        assertThat(secondEntry.getProperty('@category').toString()).isEqualTo('docs')
        assertThat((secondEntry.getProperty('title') as GPathResult).text()).isEqualTo('Second')
        assertThat((firstEntry.getProperty('author') as GPathResult).text()).isEqualTo('Ada')
        assertThat(((firstEntry.getProperty('author') as GPathResult).getProperty('@active')).toString()).isEqualTo('true')
    }

    @Test
    void markupBuilderProducesEscapedXmlWithCommentsAndRepeatedElements() {
        StringWriter writer = new StringWriter()
        MarkupBuilder builder = new MarkupBuilder(writer)
        builder.doubleQuotes = true

        builder.records(kind: 'example') {
            builder.mkp.comment('generated by MarkupBuilder')
            item(id: 'r1') {
                name('Tom & Jerry')
                tags {
                    tag('xml')
                    tag('groovy')
                }
                note('plain text is escaped: <safe>')
            }
        }

        String xml = writer.toString()
        assertThat(xml).contains('kind="example"')
        assertThat(xml).contains('Tom &amp; Jerry')
        assertThat(xml).contains('&lt;safe&gt;')
        assertThat(xml).contains('<!-- generated by MarkupBuilder -->')

        GPathResult parsed = new XmlSlurper(false, false).parseText(xml)
        GPathResult item = parsed.getProperty('item') as GPathResult
        assertThat((item.getProperty('name') as GPathResult).text()).isEqualTo('Tom & Jerry')
        assertThat((item.getProperty('tags') as GPathResult).getProperty('tag').collect { tag -> tag.text() })
                .containsExactly('xml', 'groovy')
    }

    @Test
    void domBuilderCreatesStandardDomDocuments() {
        String xml = '''
                <inventory>
                  <item id="i1"><name>Parser</name><count>2</count></item>
                  <item id="i2"><name>Builder</name><count>5</count></item>
                </inventory>
                '''.stripIndent()

        Document document = DOMBuilder.parse(new StringReader(xml))

        assertThat(document.documentElement.tagName).isEqualTo('inventory')
        assertThat(document.getElementsByTagName('item').length).isEqualTo(2)
        assertThat(document.getElementsByTagName('item').item(0).attributes.getNamedItem('id').nodeValue).isEqualTo('i1')
        assertThat(document.getElementsByTagName('name').item(1).textContent).isEqualTo('Builder')
    }

    @Test
    void xmlNodePrinterRendersParsedNodesWithConfiguredWhitespace() {
        Node root = new XmlParser(false, false).parseText('''
                <root><entry id="1">alpha</entry><entry id="2">beta</entry></root>
                '''.stripIndent())
        StringWriter writer = new StringWriter()
        XmlNodePrinter printer = new XmlNodePrinter(new PrintWriter(writer))
        printer.preserveWhitespace = true
        printer.expandEmptyElements = true

        printer.print(root)

        GPathResult parsed = new XmlSlurper(false, false).parseText(writer.toString())
        GPathResult entries = parsed.getProperty('entry') as GPathResult
        assertThat((entries.getAt(0) as GPathResult).getProperty('@id').toString()).isEqualTo('1')
        assertThat((entries.getAt(1) as GPathResult).getProperty('@id').toString()).isEqualTo('2')
        assertThat((entries.getAt(0) as GPathResult).text()).isEqualTo('alpha')
        assertThat((entries.getAt(1) as GPathResult).text()).isEqualTo('beta')
    }

    @Test
    void namespaceCreatesQualifiedNamesUsableWithParsedNodes() {
        Namespace namespace = new Namespace('urn:catalog', 'cat')
        QName entryName = namespace.get('entry')
        QName titleName = namespace.get('title')

        assertThat(titleName.localPart).isEqualTo('title')
        assertThat(titleName.namespaceURI).isEqualTo('urn:catalog')
        assertThat(titleName.qualifiedName).isEqualTo('cat:title')

        Node root = new XmlParser(false, true).parseText('''
                <records xmlns:cat="urn:catalog">
                  <cat:entry id="e1"><cat:title>Namespaced title</cat:title></cat:entry>
                </records>
                '''.stripIndent())

        Node entry = root.getAt(entryName).get(0) as Node
        assertThat(entry.getAt(titleName).get(0).text()).isEqualTo('Namespaced title')
    }
}
