/*
 * Copyright and related rights waived via CC0
 *
 * You should have received a copy of the CC0 legalcode along with this
 * work. If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
 */
package org_jetbrains_kotlin.kotlin_parcelize_runtime

import android.os.Parcel
import android.os.Parcelable
import kotlinx.parcelize.IgnoredOnParcel
import kotlinx.parcelize.Parceler
import kotlinx.parcelize.Parcelize
import kotlinx.parcelize.RawValue
import kotlinx.parcelize.TypeParceler
import kotlinx.parcelize.WriteWith
import kotlinx.parcelize.parcelableCreator
import org.assertj.core.api.Assertions.assertThat
import org.assertj.core.api.Assertions.assertThatThrownBy
import org.junit.jupiter.api.Test

public class Kotlin_parcelize_runtimeTest {
    @Test
    public fun markerAnnotationConstructorsCreateStableValueObjects() {
        val parcelize: Parcelize = Parcelize()
        val rawValue: RawValue = RawValue()
        val ignoredOnParcel: IgnoredOnParcel = IgnoredOnParcel()

        assertThat(parcelize).isEqualTo(Parcelize())
        assertThat(parcelize.hashCode()).isEqualTo(Parcelize().hashCode())
        assertThat(parcelize.toString()).contains("Parcelize")
        assertThat(rawValue).isEqualTo(RawValue())
        assertThat(rawValue.toString()).contains("RawValue")
        assertThat(ignoredOnParcel).isEqualTo(IgnoredOnParcel())
        assertThat(ignoredOnParcel.toString()).contains("IgnoredOnParcel")
    }

    @Test
    public fun parcelerTypeAnnotationsPreserveTheirGenericContractsAtCompileTime() {
        val stringTypeParceler: TypeParceler<String, StringParceler> = TypeParceler()
        val intTypeParceler: TypeParceler<Int, IntParceler> = TypeParceler()
        val writeWithStringParceler: WriteWith<StringParceler> = WriteWith()
        val writeWithIntParceler: WriteWith<IntParceler> = WriteWith()

        assertThat(stringTypeParceler).isEqualTo(TypeParceler<String, StringParceler>())
        assertThat(intTypeParceler).isEqualTo(TypeParceler<Int, IntParceler>())
        assertThat(writeWithStringParceler).isEqualTo(WriteWith<StringParceler>())
        assertThat(writeWithIntParceler).isEqualTo(WriteWith<IntParceler>())
    }

    @Test
    public fun parcelerImplementationsCanProvideTypedParcelableArrays() {
        val parceler: Parceler<String> = ArrayCreatingStringParceler
        val createdArray: Array<String> = parceler.newArray(3)

        assertThat(createdArray).containsExactly("", "", "")
        assertThat(createdArray::class.java.componentType).isEqualTo(String::class.java)
    }

    @Test
    public fun parcelerDefaultNewArrayReportsThatGenerationIsExpectedFromParcelizeTooling() {
        assertThatThrownBy { StringParceler.newArray(3) }
            .isInstanceOf(NotImplementedError::class.java)
            .hasMessage("Generated by Android Extensions automatically")
    }

    @Test
    public fun parcelableCreatorReturnsTheParcelableStaticCreatorField() {
        val creator: Parcelable.Creator<CreatorBackedParcelable> = parcelableCreator()

        assertThat(creator).isSameAs(CreatorBackedParcelable.CREATOR)
        assertThat(creator.newArray(2)).containsExactly(null, null)
    }

    @Test
    public fun parcelableCreatorRejectsCreatorFieldsWithTheWrongType() {
        assertThatThrownBy { parcelableCreator<WrongCreatorFieldParcelable>() }
            .isInstanceOf(IllegalArgumentException::class.java)
            .hasMessageContaining("Could not access CREATOR field in class")
            .hasMessageContaining("WrongCreatorFieldParcelable")
    }

    @Test
    public fun parcelableCreatorRejectsParcelableTypesWithoutCreatorFields() {
        assertThatThrownBy { parcelableCreator<MissingCreatorFieldParcelable>() }
            .isInstanceOf(NoSuchFieldException::class.java)
            .hasMessageContaining("CREATOR")
    }

    @Test
    public fun parcelizeAndTypeParcelerAnnotationsCanBeRepeatedOnRegularDomainTypes() {
        val carrier: RepeatedTypeParcelerCarrier = RepeatedTypeParcelerCarrier(
            name = "parcelized",
            count = 7
        )

        assertThat(carrier.name).isEqualTo("parcelized")
        assertThat(carrier.count).isEqualTo(7)
    }

    @Test
    public fun rawValueWriteWithAndIgnoredOnParcelCanAnnotateNestedTypeAndPropertyPositions() {
        val payload: Map<String, Any> = linkedMapOf("answer" to 42, "enabled" to true)
        val carrier: ParcelAnnotationCarrier = ParcelAnnotationCarrier(
            rawItems = listOf(payload, "literal"),
            namedRawItems = mapOf("payload" to payload),
            writtenWithStringParceler = "custom-string"
        )

        assertThat(carrier.rawItems).containsExactly(payload, "literal")
        assertThat(carrier.namedRawItems).containsEntry("payload", payload)
        assertThat(carrier.writtenWithStringParceler).isEqualTo("custom-string")
        assertThat(carrier.ignoredDerivedValue).isEqualTo("derived:2")
    }

    @Test
    public fun propertyScopedTypeParcelerAnnotationsLeaveKotlinObjectSemanticsUnchanged() {
        val first: PropertyTypeParcelerCarrier = PropertyTypeParcelerCarrier("same", 11)
        val second: PropertyTypeParcelerCarrier = first.copy()
        val changed: PropertyTypeParcelerCarrier = first.copy(count = 12)

        assertThat(second).isEqualTo(first)
        assertThat(changed).isNotEqualTo(first)
        assertThat(first.toString()).contains("same", "11")
    }
}

@Parcelize
@TypeParceler<String, StringParceler>
@TypeParceler<Int, IntParceler>
private data class RepeatedTypeParcelerCarrier(
    val name: String,
    val count: Int
)

private data class ParcelAnnotationCarrier(
    val rawItems: List<@RawValue Any>,
    val namedRawItems: Map<String, @RawValue Any>,
    val writtenWithStringParceler: @WriteWith<StringParceler> String,
    @IgnoredOnParcel val ignoredDerivedValue: String = "derived:${rawItems.size}"
)

private data class PropertyTypeParcelerCarrier(
    @property:TypeParceler<String, StringParceler> val name: String,
    @property:TypeParceler<Int, IntParceler> val count: Int
)

private object StringParceler : Parceler<String> {
    override fun create(parcel: Parcel): String = parcel.readString().orEmpty()

    override fun String.write(parcel: Parcel, flags: Int) {
        parcel.writeString(this)
    }
}

private object IntParceler : Parceler<Int> {
    override fun create(parcel: Parcel): Int = parcel.readInt()

    override fun Int.write(parcel: Parcel, flags: Int) {
        parcel.writeInt(this)
    }
}

private object ArrayCreatingStringParceler : Parceler<String> {
    override fun create(parcel: Parcel): String = parcel.readString().orEmpty()

    override fun String.write(parcel: Parcel, flags: Int) {
        parcel.writeString(this)
    }

    override fun newArray(size: Int): Array<String> = Array(size) { "" }
}

public class CreatorBackedParcelable(public val value: String) : Parcelable {
    override fun describeContents(): Int = 0

    override fun writeToParcel(parcel: Parcel, flags: Int) {
        parcel.writeString(value)
    }

    public companion object {
        @JvmField
        public val CREATOR: Parcelable.Creator<CreatorBackedParcelable> = object : Parcelable.Creator<CreatorBackedParcelable> {
            override fun createFromParcel(source: Parcel): CreatorBackedParcelable = CreatorBackedParcelable(
                source.readString().orEmpty()
            )

            override fun newArray(size: Int): Array<CreatorBackedParcelable?> = arrayOfNulls(size)
        }
    }
}

public class WrongCreatorFieldParcelable : Parcelable {
    override fun describeContents(): Int = 0

    override fun writeToParcel(parcel: Parcel, flags: Int) = Unit

    public companion object {
        @JvmField
        public val CREATOR: String = "not-a-parcelable-creator"
    }
}

public class MissingCreatorFieldParcelable : Parcelable {
    override fun describeContents(): Int = 0

    override fun writeToParcel(parcel: Parcel, flags: Int) = Unit
}
