/*
 * Copyright and related rights waived via CC0
 *
 * You should have received a copy of the CC0 legalcode along with this
 * work. If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
 */
package org_apache_maven_doxia.doxia_site_renderer;

import java.io.InputStream;
import java.nio.charset.StandardCharsets;

import org.apache.maven.doxia.siterenderer.SkinResourceLoader;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class SkinResourceLoaderTest {
    @Test
    void getResourceStreamLoadsTemplateFromContextClassLoader() throws Exception {
        ClassLoader originalClassLoader = Thread.currentThread().getContextClassLoader();
        Thread.currentThread().setContextClassLoader(SkinResourceLoader.class.getClassLoader());
        try {
            SkinResourceLoader loader = new SkinResourceLoader();

            try (InputStream stream = loader.getResourceStream(
                    "/org/apache/maven/doxia/siterenderer/resources/default-site.vm")) {
                assertThat(stream).isNotNull();

                String content = new String(stream.readAllBytes(), StandardCharsets.UTF_8);

                assertThat(content).contains("Generated by Apache Maven Doxia Site Renderer");
            }
        } finally {
            Thread.currentThread().setContextClassLoader(originalClassLoader);
        }
    }
}
