function com_google_gwt_core_Core_JUnit(){var N='bootstrap',O='begin',P='gwt.codesvr.com.google.gwt.core.Core.JUnit=',Q='gwt.codesvr=',R='com.google.gwt.core.Core.JUnit',S='startup',T='DUMMY',U=0,V=1,W='iframe',X='position:absolute; width:0; height:0; border:none; left: -1000px;',Y=' top: -1000px;',Z='Chrome',$='CSS1Compat',_='<!doctype html>',ab='',bb='<html><head><\/head><body><\/body><\/html>',cb='undefined',db='readystatechange',eb=10,fb='script',gb='moduleStartup',hb='moduleRequested',ib='com_google_gwt_core_Core_JUnit',jb='Failed to load ',kb='head',lb='javascript',mb='meta',nb='name',ob='com.google.gwt.core.Core.JUnit::',pb='::',qb='gwt:property',rb='content',sb='=',tb='gwt:onPropertyErrorFn',ub='Bad handler "',vb='" for "gwt:onPropertyErrorFn"',wb='gwt:onLoadErrorFn',xb='" for "gwt:onLoadErrorFn"',yb='#',zb='?',Ab='/',Bb='img',Cb='clear.cache.gif',Db='baseUrl',Eb='com.google.gwt.core.Core.JUnit.nocache.js',Fb='base',Gb='//',Hb='user.agent',Ib='webkit',Jb='safari',Kb='gecko',Lb=11,Mb='gecko1_8',Nb='selectingPermutation',Ob='com.google.gwt.core.Core.JUnit.devmode.js',Pb="GWT module 'com.google.gwt.core.Core.JUnit' may need to be (re)compiled",Qb=':',Rb='.cache.js',Sb='loadExternalRefs',Tb='end',Ub='http:',Vb='file:',Wb='_gwt_dummy_',Xb='__gwtDevModeHook:com.google.gwt.core.Core.JUnit',Yb='Ignoring non-whitelisted Dev Mode URL: ',Zb=':moduleBase';var n=window;var o=document;q(N,O);function p(){var a=n.location.search;return a.indexOf(P)!=-1||a.indexOf(Q)!=-1}
function q(a,b){if(n.__gwtStatsEvent){n.__gwtStatsEvent({moduleName:R,sessionId:n.__gwtStatsSessionId,subSystem:S,evtGroup:a,millis:(new Date).getTime(),type:b})}}
com_google_gwt_core_Core_JUnit.__sendStats=q;com_google_gwt_core_Core_JUnit.__moduleName=R;com_google_gwt_core_Core_JUnit.__errFn=null;com_google_gwt_core_Core_JUnit.__moduleBase=T;com_google_gwt_core_Core_JUnit.__softPermutationId=U;com_google_gwt_core_Core_JUnit.__computePropValue=null;com_google_gwt_core_Core_JUnit.__getPropMap=null;com_google_gwt_core_Core_JUnit.__installRunAsyncCode=function(){};com_google_gwt_core_Core_JUnit.__gwtStartLoadingFragment=function(){return null};com_google_gwt_core_Core_JUnit.__gwt_isKnownPropertyValue=function(){return false};com_google_gwt_core_Core_JUnit.__gwt_getMetaProperty=function(){return null};var r=null;var s=n.__gwt_activeModules=n.__gwt_activeModules||{};s[R]={moduleName:R};com_google_gwt_core_Core_JUnit.__moduleStartupDone=function(e){var f=s[R].bindings;s[R].bindings=function(){var a=f?f():{};var b=e[com_google_gwt_core_Core_JUnit.__softPermutationId];for(var c=U;c<b.length;c++){var d=b[c];a[d[U]]=d[V]}return a}};var t;function u(){v();return t}
function v(){if(t){return}var a=o.createElement(W);a.id=R;a.style.cssText=X+Y;a.tabIndex=-1;o.body.appendChild(a);t=a.contentWindow.document;if(navigator.userAgent.indexOf(Z)==-1){t.open();var b=document.compatMode==$?_:ab;t.write(b+bb);t.close()}}
function w(i){function j(a){function b(){if(typeof o.readyState==cb){return typeof o.body!=cb&&o.body!=null}return /loaded|complete/.test(o.readyState)}
var c=b();if(c){a();return}function d(){if(!c){if(!b()){return}c=true;a();if(o.removeEventListener){o.removeEventListener(db,d,false)}if(e){clearInterval(e)}}}
if(o.addEventListener){o.addEventListener(db,d,false)}var e=setInterval(function(){d()},eb)}
function k(c){function d(a,b){a.removeChild(b)}
var e=u();var f=e.body;var g;if(navigator.userAgent.indexOf(Z)>-1){g=e.createElement(fb);g.text=c.join(ab);f.appendChild(g);d(f,g)}else{for(var h=U;h<c.length;h++){g=e.createElement(fb);g.text=c[h];f.appendChild(g);d(f,g)}}}
com_google_gwt_core_Core_JUnit.onScriptDownloaded=function(a){j(function(){k(a)})};q(gb,hb);var l=o.createElement(fb);l.src=i;if(com_google_gwt_core_Core_JUnit.__errFn){l.onerror=function(){com_google_gwt_core_Core_JUnit.__errFn(ib,new Error(jb+code))}}o.getElementsByTagName(kb)[U].appendChild(l)}
com_google_gwt_core_Core_JUnit.__startLoadingFragment=function(a){return C(a)};com_google_gwt_core_Core_JUnit.__installRunAsyncCode=function(a){var b=u();var c=b.body;var d=b.createElement(fb);d.language=lb;d.text=a;c.appendChild(d);c.removeChild(d)};function A(){var c={};var d;var e;var f=o.getElementsByTagName(mb);for(var g=U,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(nb),k;if(j){j=j.replace(ob,ab);if(j.indexOf(pb)>=U){continue}if(j==qb){k=i.getAttribute(rb);if(k){var l,m=k.indexOf(sb);if(m>=U){j=k.substring(U,m);l=k.substring(m+V)}else{j=k;l=ab}c[j]=l}}else if(j==tb){k=i.getAttribute(rb);if(k){try{d=eval(k)}catch(a){alert(ub+k+vb)}}}else if(j==wb){k=i.getAttribute(rb);if(k){try{e=eval(k)}catch(a){alert(ub+k+xb)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};r=d;com_google_gwt_core_Core_JUnit.__errFn=e}
function B(){function e(a){var b=a.lastIndexOf(yb);if(b==-1){b=a.length}var c=a.indexOf(zb);if(c==-1){c=a.length}var d=a.lastIndexOf(Ab,Math.min(c,b));return d>=U?a.substring(U,d+V):ab}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=o.createElement(Bb);b.src=a+Cb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Db);if(a!=null){return a}return ab}
function h(){var a=o.getElementsByTagName(fb);for(var b=U;b<a.length;++b){if(a[b].src.indexOf(Eb)!=-1){return e(a[b].src)}}return ab}
function i(){var a=o.getElementsByTagName(Fb);if(a.length>U){return a[a.length-V].href}return ab}
function j(){var a=o.location;return a.href==a.protocol+Gb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==ab){k=h()}if(k==ab){k=i()}if(k==ab&&j()){k=e(o.location.href)}k=f(k);return k}
function C(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return com_google_gwt_core_Core_JUnit.__moduleBase+a}
function D(){var f=[];var g=U;var h=[];var i=[];function j(a){var b=i[a](),c=h[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(r){r(a,d,b)}throw null}
i[Hb]=function(){var a=navigator.userAgent.toLowerCase();var b=o.documentMode;if(function(){return a.indexOf(Ib)!=-1}())return Jb;if(function(){return a.indexOf(Kb)!=-1||b>=Lb}())return Mb;return ab};h[Hb]={'gecko1_8':U,'safari':V};__gwt_isKnownPropertyValue=function(a,b){return b in h[a]};com_google_gwt_core_Core_JUnit.__getPropMap=function(){var a={};for(var b in h){if(h.hasOwnProperty(b)){a[b]=j(b)}}return a};com_google_gwt_core_Core_JUnit.__computePropValue=j;n.__gwt_activeModules[R].bindings=com_google_gwt_core_Core_JUnit.__getPropMap;q(N,Nb);if(p()){return C(Ob)}var k;try{alert(Pb);return;var l=k.indexOf(Qb);if(l!=-1){g=parseInt(k.substring(l+V),eb);k=k.substring(U,l)}}catch(a){}com_google_gwt_core_Core_JUnit.__softPermutationId=g;return C(k+Rb)}
function F(){if(!n.__gwt_stylesLoaded){n.__gwt_stylesLoaded={}}q(Sb,O);q(Sb,Tb)}
A();com_google_gwt_core_Core_JUnit.__moduleBase=B();s[R].moduleBase=com_google_gwt_core_Core_JUnit.__moduleBase;var G=D();if(n){var H=!!(n.location.protocol==Ub||n.location.protocol==Vb);n.__gwt_activeModules[R].canRedirect=H;function I(){var b=Wb;try{n.sessionStorage.setItem(b,b);n.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(H&&I()){var J=Xb;var K=n.sessionStorage[J];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(K)){if(K&&(window.console&&console.log)){console.log(Yb+K)}K=ab}if(K&&!n[J]){n[J]=true;n[J+Zb]=B();var L=o.createElement(fb);L.src=K;var M=o.getElementsByTagName(kb)[U];M.insertBefore(L,M.firstElementChild||M.children[U]);return false}}}F();q(N,Tb);w(G);return true}
com_google_gwt_core_Core_JUnit.succeeded=com_google_gwt_core_Core_JUnit();