package org.graalvm.internal.tck.utils;

import java.nio.file.Path;
import java.util.Scanner;
import java.util.function.Function;

public class InteractiveTaskUtils {
    public static <R> R askQuestion(String question, String helpMessage, Function<String, R> handleAnswer) {
        Scanner scanner = new Scanner(System.in);

        while (true) {
            printQuestion(question);

            String answer = scanner.next();
            if (answer.equalsIgnoreCase("help")) {
                printHelpMessage(helpMessage);
                continue;
            }

            try {
                return handleAnswer.apply(answer);
            } catch (IllegalStateException ex) {
                printErrorMessage(ex.getMessage());
            }
        }
    }

    public static boolean askYesNoQuestion(String question, String helpMessage, boolean defaultAnswer) {
        Scanner scanner = new Scanner(System.in);

        while (true) {
            printQuestion(question);

            String answer = scanner.nextLine();
            if (answer.equalsIgnoreCase("help")) {
                printHelpMessage(helpMessage);
                continue;
            }

            if (answer.isEmpty()) {
                return defaultAnswer;
            }

            if (answer.equalsIgnoreCase("y")) {
                return true;
            }

            if (answer.equalsIgnoreCase("n")) {
                return false;
            }

            printErrorMessage("Your answer must be either y (for yes) or n (for no)");
        }
    }

    public static boolean askForDeletePermission(Path file) {
        String question = "Please double check that the task can remove the following file: " + file +
                ". If this file is not generated by the task, please report the error on the metadata repository. " +
                "Can the task delete this file? [y/N]";
        String help = "The task should only remove dummy files generated in the previous step. Please verify that the following file can be removed: " + file;

        return askYesNoQuestion(question, help, false);
    }

    public static void closeSection() {
        ColoredOutput.println("------------------------------------------------------------------------------------------", ColoredOutput.OUTPUT_COLOR.BLUE);
    }

    public static void printUserInfo(String message) {
        ColoredOutput.println("[INFO] " + message + "...", ColoredOutput.OUTPUT_COLOR.BLUE);
        waitForUserToReadMessage();
    }

    public static void printSuccessfulStatement(String message) {
        ColoredOutput.println("[SUCCESS] " + message, ColoredOutput.OUTPUT_COLOR.GREEN);
        waitForUserToReadMessage();
    }

    public static void printErrorMessage(String message) {
        ColoredOutput.println("[ERROR] " + message, ColoredOutput.OUTPUT_COLOR.RED);
        waitForUserToReadMessage();
    }

    public static void printHelpMessage(String helpMessage) {
        ColoredOutput.println("[HELP] " + helpMessage, ColoredOutput.OUTPUT_COLOR.YELLOW);
        waitForUserToReadMessage();
    }

    private static void printQuestion(String question) {
        ColoredOutput.println("[QUESTION] " + question, ColoredOutput.OUTPUT_COLOR.GREEN);
    }

    private static void waitForUserToReadMessage() {
        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            throw new RuntimeException("Waiting for user to read the message was interrupted. Reason: " + e.getMessage());
        }
    }

}
