name: "💡 Feature request"
description: Suggest an idea for this project
title: "Feature: "
labels:
  - enhancement
assignees:
  - vjovanov

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: Describe the problem you're facing. What are you trying to accomplish? Why is it important?
      placeholder: I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: Clearly describe what you want to happen. Include details about expected behavior and scope.
      placeholder: I would like [...]
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: List any alternative solutions or workarounds you've tried or considered.
      placeholder: Alternatives or workarounds [...]
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Screenshots, references, related issues/PRs, etc. (optional)
    validations:
      required: false
