/*
 * Copyright and related rights waived via CC0
 *
 * You should have received a copy of the CC0 legalcode along with this
 * work. If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
 */
package org_aesh.aesh;

import static org.assertj.core.api.Assertions.assertThat;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

import org.aesh.command.AeshCommandRuntimeBuilder;
import org.aesh.command.Command;
import org.aesh.command.CommandDefinition;
import org.aesh.command.CommandResult;
import org.aesh.command.CommandRuntime;
import org.aesh.command.impl.registry.AeshCommandRegistryBuilder;
import org.aesh.command.invocation.CommandInvocation;
import org.aesh.command.option.Option;
import org.aesh.command.registry.CommandRegistry;
import org.aesh.util.completer.CompleterCommand;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class CompleterCommandTest {
    private static final Path GENERATED_COMPLETION_FILE = Path.of("metadatacompletiontarget_complete.bash");

    @BeforeEach
    void deleteStaleCompletionFile() throws Exception {
        Files.deleteIfExists(GENERATED_COMPLETION_FILE);
    }

    @AfterEach
    void deleteGeneratedCompletionFile() throws Exception {
        Files.deleteIfExists(GENERATED_COMPLETION_FILE);
    }

    @Test
    void completerCommandLoadsCommandClassByNameAndWritesBashCompletionFile() throws Exception {
        CommandRuntime<CommandInvocation> runtime = runtimeFor(CompleterCommand.class);

        CommandResult result = runtime.executeCommand("completer " + CompletionTargetCommand.class.getName());

        assertThat(result).isEqualTo(CommandResult.SUCCESS);
        assertThat(GENERATED_COMPLETION_FILE).exists().isRegularFile();
        assertThat(Files.readString(GENERATED_COMPLETION_FILE, StandardCharsets.UTF_8))
                .contains("Completion support for metadatacompletiontarget generated by Aesh")
                .contains("function _complete_metadatacompletiontarget")
                .contains("--message")
                .contains("complete -F _complete_metadatacompletiontarget");
    }

    private static CommandRuntime<CommandInvocation> runtimeFor(Class<? extends Command> command) throws Exception {
        CommandRegistry<CommandInvocation> registry = AeshCommandRegistryBuilder.<CommandInvocation>builder()
                .command(command)
                .create();
        return AeshCommandRuntimeBuilder.<CommandInvocation>builder()
                .commandRegistry(registry)
                .build();
    }

    @CommandDefinition(name = "metadatacompletiontarget", description = "Command used by the completion generator test")
    public static class CompletionTargetCommand implements Command<CommandInvocation> {
        @Option(name = "message", defaultValue = {"hello"}, description = "Message to include in generated completion")
        private String message;

        @Override
        public CommandResult execute(CommandInvocation commandInvocation) {
            return CommandResult.SUCCESS;
        }
    }
}
