/*
 * Copyright and related rights waived via CC0
 *
 * You should have received a copy of the CC0 legalcode along with this
 * work. If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
 */
package org_gwtproject.gwt_user;

import static org.assertj.core.api.Assertions.assertThat;

import com.google.gwt.user.tools.WebAppCreator;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.MethodType;
import java.net.URL;
import java.nio.file.Path;

public class WebAppCreatorTest {
    private static final String MODULE_NAME = "org_gwtproject.gwt_user.coverage.CoverageApp";

    @TempDir
    private Path outputDirectory;

    @Test
    void mainFlowGeneratesReadmeTemplateFromClasspathResources() throws Throwable {
        final boolean canReadTemplateTree = canWebAppCreatorReadTemplateTree();

        final boolean generated = invokeDoMain(
                "-templates", "readme",
                "-out", outputDirectory.toString(),
                MODULE_NAME);

        assertThat(generated).isEqualTo(canReadTemplateTree);
        if (canReadTemplateTree) {
            assertThat(outputDirectory.resolve("README.txt"))
                    .exists()
                    .content()
                    .contains("Generated by GWT WebAppCreator")
                    .contains("CoverageApp");
        } else {
            assertThat(outputDirectory.resolve("README.txt")).doesNotExist();
        }
    }

    private static boolean canWebAppCreatorReadTemplateTree() {
        final URL templateRoot = WebAppCreator.class.getResource("templates/readme");
        if (templateRoot == null) {
            return false;
        }
        final String protocol = templateRoot.getProtocol();
        return "file".equals(protocol) || "jar".equals(protocol);
    }

    private static boolean invokeDoMain(final String... args) throws Throwable {
        // WebAppCreator.main exits the JVM; doMain exercises the same non-exiting flow.
        final MethodHandle doMain = MethodHandles.privateLookupIn(
                        WebAppCreator.class,
                        MethodHandles.lookup())
                .findStatic(
                        WebAppCreator.class,
                        "doMain",
                        MethodType.methodType(boolean.class, String[].class));
        return (boolean) doMain.asFixedArity().invoke((Object) args);
    }
}
