/*
 * Copyright and related rights waived via CC0
 *
 * You should have received a copy of the CC0 legalcode along with this
 * work. If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
 */
package org_apache_maven.maven_archiver;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.io.InputStream;
import java.io.Reader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Properties;
import java.util.jar.JarEntry;
import java.util.jar.JarFile;

import org.apache.maven.archiver.PomPropertiesUtil;
import org.apache.maven.model.Model;
import org.apache.maven.project.MavenProject;
import org.codehaus.plexus.archiver.jar.JarArchiver;
import org.junit.jupiter.api.Test;

public class PomPropertiesUtilTest {
    @Test
    void createPomPropertiesWritesProjectCoordinatesAndAddsThemToArchive() throws Exception {
        Path testDirectory = testDirectory("archive-pom-properties");
        Path pomPropertiesFile = testDirectory.resolve("generated/pom.properties");
        Path archiveFile = testDirectory.resolve("application.jar");
        MavenProject project = newProject("com.acme", "service", "1.0.0");
        JarArchiver archiver = new JarArchiver();
        archiver.setDestFile(archiveFile.toFile());

        new PomPropertiesUtil().createPomProperties(project, archiver, pomPropertiesFile.toFile(), false);
        archiver.createArchive();

        assertCoordinates(loadProperties(pomPropertiesFile), "com.acme", "service", "1.0.0");
        try (JarFile jarFile = new JarFile(archiveFile.toFile())) {
            JarEntry entry = jarFile.getJarEntry("META-INF/maven/com.acme/service/pom.properties");
            assertNotNull(entry);
            try (InputStream inputStream = jarFile.getInputStream(entry)) {
                assertCoordinates(loadProperties(inputStream), "com.acme", "service", "1.0.0");
            }
        }
    }

    @Test
    void createPomPropertiesKeepsMatchingExistingFileWhenNotForced() throws Exception {
        Path testDirectory = testDirectory("preserve-existing-pom-properties");
        Path pomPropertiesFile = testDirectory.resolve("pom.properties");
        Files.writeString(pomPropertiesFile, """
                # preserved by the test
                artifactId=service
                groupId=com.acme
                version=1.0.0
                """, StandardCharsets.ISO_8859_1);

        new PomPropertiesUtil().createPomProperties(
                newProject("com.acme", "service", "1.0.0"), new JarArchiver(), pomPropertiesFile.toFile(), false);

        String content = Files.readString(pomPropertiesFile, StandardCharsets.ISO_8859_1);
        assertTrue(content.contains("# preserved by the test"));
        assertFalse(content.contains("Generated by Maven"));
        assertCoordinates(loadProperties(pomPropertiesFile), "com.acme", "service", "1.0.0");
    }

    @Test
    void createPomPropertiesRewritesExistingFileWhenForced() throws Exception {
        Path testDirectory = testDirectory("force-pom-properties");
        Path pomPropertiesFile = testDirectory.resolve("pom.properties");
        Files.writeString(pomPropertiesFile, """
                # preserved by the test
                artifactId=service
                groupId=com.acme
                version=1.0.0
                """, StandardCharsets.ISO_8859_1);

        new PomPropertiesUtil().createPomProperties(
                newProject("com.acme", "service", "1.0.0"), new JarArchiver(), pomPropertiesFile.toFile(), true);

        String content = Files.readString(pomPropertiesFile, StandardCharsets.ISO_8859_1);
        assertFalse(content.contains("# preserved by the test"));
        assertTrue(content.contains("Generated by Maven"));
        assertCoordinates(loadProperties(pomPropertiesFile), "com.acme", "service", "1.0.0");
    }

    @Test
    void createPomPropertiesRewritesDifferentExistingFileEvenWhenNotForced() throws Exception {
        Path testDirectory = testDirectory("rewrite-different-pom-properties");
        Path pomPropertiesFile = testDirectory.resolve("pom.properties");
        Files.writeString(pomPropertiesFile, """
                # stale coordinates
                artifactId=service
                groupId=com.acme
                version=0.9.0
                """, StandardCharsets.ISO_8859_1);

        new PomPropertiesUtil().createPomProperties(
                newProject("com.acme", "service", "1.0.0"), new JarArchiver(), pomPropertiesFile.toFile(), false);

        String content = Files.readString(pomPropertiesFile, StandardCharsets.ISO_8859_1);
        assertFalse(content.contains("# stale coordinates"));
        assertTrue(content.contains("Generated by Maven"));
        assertCoordinates(loadProperties(pomPropertiesFile), "com.acme", "service", "1.0.0");
    }

    private static Path testDirectory(String name) throws IOException {
        Path baseDirectory = Path.of("build", "test-work", PomPropertiesUtilTest.class.getSimpleName());
        Files.createDirectories(baseDirectory);
        return Files.createTempDirectory(baseDirectory, name + "-");
    }

    private static MavenProject newProject(String groupId, String artifactId, String version) {
        Model model = new Model();
        model.setGroupId(groupId);
        model.setArtifactId(artifactId);
        model.setVersion(version);
        return new MavenProject(model);
    }

    private static Properties loadProperties(Path path) throws IOException {
        try (Reader reader = Files.newBufferedReader(path, StandardCharsets.ISO_8859_1)) {
            Properties properties = new Properties();
            properties.load(reader);
            return properties;
        }
    }

    private static Properties loadProperties(InputStream inputStream) throws IOException {
        Properties properties = new Properties();
        properties.load(inputStream);
        return properties;
    }

    private static void assertCoordinates(Properties properties, String groupId, String artifactId, String version) {
        assertEquals(groupId, properties.getProperty("groupId"));
        assertEquals(artifactId, properties.getProperty("artifactId"));
        assertEquals(version, properties.getProperty("version"));
    }
}
