/*
 * Copyright and related rights waived via CC0
 *
 * You should have received a copy of the CC0 legalcode along with this
 * work. If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
 */
package org_hsqldb.hsqldb;

import static org.assertj.core.api.Assertions.assertThat;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.UUID;

import org.hsqldb.jdbc.JDBCDataSource;
import org.hsqldb.lib.ArrayUtil;
import org.junit.jupiter.api.Test;

public class ArrayUtilTest {
    @Test
    void duplicateArrayCreatesIndependentPrimitiveArrayWithSameElements() {
        int[] source = new int[] {7, 11, 13 };

        Object duplicate = ArrayUtil.duplicateArray(source);

        assertThat(duplicate).isInstanceOf(int[].class);
        assertThat((int[]) duplicate).containsExactly(7, 11, 13);
        assertThat(duplicate).isNotSameAs(source);
    }

    @Test
    void resizeArrayAlwaysCreatesPrimitiveArrayWithRequestedSize() {
        int[] source = new int[] {2, 3, 5 };

        Object resized = ArrayUtil.resizeArray(source, 5);

        assertThat(resized).isInstanceOf(int[].class);
        assertThat((int[]) resized).containsExactly(2, 3, 5, 0, 0);
        assertThat(resized).isNotSameAs(source);
    }

    @Test
    void resizeArrayIfDifferentCreatesPrimitiveArrayOnlyWhenSizeChanges() {
        int[] source = new int[] {17, 19, 23 };

        Object resized = ArrayUtil.resizeArrayIfDifferent(source, 2);

        assertThat(resized).isInstanceOf(int[].class);
        assertThat((int[]) resized).containsExactly(17, 19);
        assertThat(resized).isNotSameAs(source);
    }

    @Test
    void toAdjustedArrayInsertsPrimitiveElementAtRequestedIndex() {
        int[] source = new int[] {29, 37 };

        Object adjusted = ArrayUtil.toAdjustedArray(source, 31, 1, 1);

        assertThat(adjusted).isInstanceOf(int[].class);
        assertThat((int[]) adjusted).containsExactly(29, 31, 37);
        assertThat(adjusted).isNotSameAs(source);
    }

    @Test
    void embeddedTableChangesExerciseArrayUtilitiesUsedByDatabaseEngine() throws Exception {
        try (Connection connection = openConnection();
                Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE array_util_target(
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        label VARCHAR(20))
                    """);
            statement.execute("""
                    ALTER TABLE array_util_target
                    ADD COLUMN flag BOOLEAN DEFAULT FALSE
                    """);
            statement.execute("CREATE INDEX array_util_target_label_idx ON array_util_target(label)");
            statement.execute("INSERT INTO array_util_target(label) VALUES ('first')");
            statement.execute("UPDATE array_util_target SET flag = TRUE WHERE label = 'first'");

            try (ResultSet resultSet = statement.executeQuery("""
                    SELECT label, flag FROM array_util_target
                    WHERE label = 'first'
                    """)) {
                assertThat(resultSet.next()).isTrue();
                assertThat(resultSet.getString(1)).isEqualTo("first");
                assertThat(resultSet.getBoolean(2)).isTrue();
                assertThat(resultSet.next()).isFalse();
            }

            statement.execute("ALTER TABLE array_util_target DROP COLUMN flag");
        }
    }

    private static Connection openConnection() throws SQLException {
        JDBCDataSource dataSource = new JDBCDataSource();

        dataSource.setUrl("jdbc:hsqldb:mem:" + randomDatabaseName() + ";shutdown=true");
        dataSource.setUser("SA");
        dataSource.setPassword("");

        return dataSource.getConnection();
    }

    private static String randomDatabaseName() {
        return "ArrayUtilTest" + UUID.randomUUID().toString().replace("-", "");
    }
}
