/*
 * Copyright and related rights waived via CC0
 *
 * You should have received a copy of the CC0 legalcode along with this
 * work. If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
 */
package org_hsqldb.hsqldb;

import static org.assertj.core.api.Assertions.assertThat;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.util.UUID;

import org.hsqldb.jdbc.JDBCColumnMetaData;
import org.hsqldb.jdbc.JDBCDataSource;
import org.hsqldb.jdbc.JDBCResultSetMetaData;
import org.junit.jupiter.api.Test;

public class JDBCColumnMetaDataTest {
    @Test
    void rendersColumnMetadataStructure() {
        JDBCColumnMetaData metadata = new JDBCColumnMetaData();

        metadata.catalogName = "PUBLIC";
        metadata.columnClassName = String.class.getName();
        metadata.columnDisplaySize = 32;
        metadata.columnLabel = "ITEM_NAME";
        metadata.columnName = "NAME";
        metadata.columnType = Types.VARCHAR;
        metadata.precision = 32;
        metadata.scale = 0;
        metadata.schemaName = "PUBLIC";
        metadata.tableName = "ITEMS";
        metadata.isAutoIncrement = false;
        metadata.isCaseSensitive = true;
        metadata.isCurrency = false;
        metadata.isDefinitelyWritable = false;
        metadata.isNullable = ResultSetMetaData.columnNoNulls;
        metadata.isReadOnly = false;
        metadata.isSearchable = true;
        metadata.isSigned = false;
        metadata.isWritable = true;

        String description = String.valueOf(metadata);

        assertThat(description)
                .startsWith("[")
                .endsWith("]")
                .contains("catalogName=PUBLIC")
                .contains("columnClassName=java.lang.String")
                .contains("columnDisplaySize=32")
                .contains("columnLabel=ITEM_NAME")
                .contains("columnName=NAME")
                .contains("columnType=12")
                .contains("precision=32")
                .contains("scale=0")
                .contains("schemaName=PUBLIC")
                .contains("tableName=ITEMS")
                .contains("isAutoIncrement=false")
                .contains("isCaseSensitive=true")
                .contains("isCurrency=false")
                .contains("isDefinitelyWritable=false")
                .contains("isNullable=0")
                .contains("isReadOnly=false")
                .contains("isSearchable=true")
                .contains("isSigned=false")
                .contains("isWritable=true");
    }

    @Test
    void rendersJdbcResultSetColumnMetadata() throws SQLException {
        try (Connection connection = openConnection();
                Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE ITEMS (
                        ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        NAME VARCHAR(32) NOT NULL
                    )
                    """);
            statement.executeUpdate("INSERT INTO ITEMS(NAME) VALUES ('alpha')");

            try (ResultSet resultSet = statement.executeQuery("SELECT ID, NAME FROM ITEMS")) {
                assertThat(resultSet.next()).isTrue();

                ResultSetMetaData metadata = resultSet.getMetaData();

                assertThat(metadata).isInstanceOf(JDBCResultSetMetaData.class);

                JDBCResultSetMetaData jdbcMetadata = (JDBCResultSetMetaData) metadata;
                String description = jdbcMetadata.toString();

                assertThat(description)
                        .contains("column_1=")
                        .contains("column_2=")
                        .contains("columnName=ID")
                        .contains("columnLabel=ID")
                        .contains("columnClassName=")
                        .contains("columnDisplaySize=")
                        .contains("columnName=NAME")
                        .contains("columnLabel=NAME")
                        .contains("isNullable=");
            }
        }
    }

    private static Connection openConnection() throws SQLException {
        JDBCDataSource dataSource = new JDBCDataSource();
        String databaseName = "JDBCColumnMetaDataTest"
                + UUID.randomUUID().toString().replace("-", "");

        dataSource.setUrl("jdbc:hsqldb:mem:" + databaseName + ";shutdown=true");
        dataSource.setUser("SA");
        dataSource.setPassword("");

        return dataSource.getConnection();
    }
}
