/*
 * Copyright and related rights waived via CC0
 *
 * You should have received a copy of the CC0 legalcode along with this
 * work. If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
 */
package io_github_pdvrieze_xmlutil.core_jvmcommon

import nl.adaptivity.xmlutil.EventType
import nl.adaptivity.xmlutil.ExperimentalXmlUtilApi
import nl.adaptivity.xmlutil.XmlBufferedReader
import nl.adaptivity.xmlutil.XmlDeclMode
import nl.adaptivity.xmlutil.XmlEvent
import nl.adaptivity.xmlutil.XmlReader
import nl.adaptivity.xmlutil.XmlWriter
import nl.adaptivity.xmlutil.dom2.Attr
import nl.adaptivity.xmlutil.dom2.CharacterData
import nl.adaptivity.xmlutil.dom2.Element
import nl.adaptivity.xmlutil.dom2.Node
import nl.adaptivity.xmlutil.dom2.NodeType
import nl.adaptivity.xmlutil.dom2.attributes
import nl.adaptivity.xmlutil.dom2.childNodes
import nl.adaptivity.xmlutil.dom2.data
import nl.adaptivity.xmlutil.dom2.documentElement
import nl.adaptivity.xmlutil.dom2.length
import nl.adaptivity.xmlutil.dom2.name
import nl.adaptivity.xmlutil.dom2.namespaceURI
import nl.adaptivity.xmlutil.dom2.nextSibling
import nl.adaptivity.xmlutil.dom2.nodeName
import nl.adaptivity.xmlutil.dom2.ownerElement
import nl.adaptivity.xmlutil.dom2.parentNode
import nl.adaptivity.xmlutil.dom2.prefix
import nl.adaptivity.xmlutil.dom2.previousSibling
import nl.adaptivity.xmlutil.dom2.publicId
import nl.adaptivity.xmlutil.dom2.systemId
import nl.adaptivity.xmlutil.dom2.target
import nl.adaptivity.xmlutil.dom2.textContent
import nl.adaptivity.xmlutil.dom2.value
import nl.adaptivity.xmlutil.elementToFragment
import nl.adaptivity.xmlutil.isElement
import nl.adaptivity.xmlutil.newWriter
import nl.adaptivity.xmlutil.readSimpleElement
import nl.adaptivity.xmlutil.serialize
import nl.adaptivity.xmlutil.skipElement
import nl.adaptivity.xmlutil.util.CompactFragment
import nl.adaptivity.xmlutil.writeAttribute
import nl.adaptivity.xmlutil.writeListIfNotEmpty
import nl.adaptivity.xmlutil.writeSimpleElement
import nl.adaptivity.xmlutil.xmlStreaming
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test
import javax.xml.namespace.QName

public class CoreJvmcommonTest {
    @Test
    fun streamingWriterEscapesNamespacesAndMixedContentForReaderRoundTrip(): Unit {
        val xml: String = buildXml { writer: XmlWriter ->
            writer.startDocument("1.0", "UTF-8", true)
            writer.processingInstruction("xml-stylesheet", "href=\"catalog.xsl\" type=\"text/xsl\"")
            writer.comment("generated by xmlutil")
            writer.setPrefix("bk", BOOK_NS)
            writer.startTag(BOOK_NS, "catalog", "bk")
            writer.namespaceAttr("bk", BOOK_NS)
            writer.attribute("", "lang", "", "en & nl")
            writer.startTag(BOOK_NS, "book", "bk")
            writer.attribute("", "id", "", "b-1")
            writer.attribute(BOOK_NS, "code", "bk", "A&B")
            writer.text("Tom & Jerry <XML>")
            writer.safeCdsect(" with CDATA end marker ]]> safely split")
            writer.endTag(BOOK_NS, "book", "bk")
            writer.endTag(BOOK_NS, "catalog", "bk")
            writer.endDocument()
        }

        assertThat(xml)
            .contains("Tom &amp; Jerry &lt;XML&gt;")
            .contains("CDATA end marker")
            .contains("xmlns:bk=\"$BOOK_NS\"")

        xmlStreaming.newGenericReader(xml).use { reader: XmlReader ->
            val startNames: MutableList<QName> = mutableListOf()
            val textContent: StringBuilder = StringBuilder()
            var sawStylesheetInstruction: Boolean = false
            var sawGeneratedComment: Boolean = false

            while (reader.hasNext()) {
                when (reader.next()) {
                    EventType.START_ELEMENT -> {
                        startNames += reader.name
                        if (reader.localName == "catalog") {
                            assertThat(reader.namespaceURI).isEqualTo(BOOK_NS)
                            assertThat(reader.getAttributeValue("", "lang")).isEqualTo("en & nl")
                            assertThat(reader.namespaceDecls.map { it.prefix to it.namespaceURI })
                                .contains("bk" to BOOK_NS)
                        }
                        if (reader.localName == "book") {
                            assertThat(reader.prefix).isEqualTo("bk")
                            assertThat(reader.getAttributeValue("", "id")).isEqualTo("b-1")
                            assertThat(reader.getAttributeValue(BOOK_NS, "code")).isEqualTo("A&B")
                        }
                    }
                    EventType.TEXT, EventType.CDSECT -> textContent.append(reader.text)
                    EventType.PROCESSING_INSTRUCTION -> {
                        sawStylesheetInstruction = reader.piTarget == "xml-stylesheet" &&
                            reader.piData.contains("catalog.xsl")
                    }
                    EventType.COMMENT -> sawGeneratedComment = reader.text == "generated by xmlutil"
                    else -> Unit
                }
            }

            assertThat(startNames).containsExactly(
                QName(BOOK_NS, "catalog", "bk"),
                QName(BOOK_NS, "book", "bk"),
            )
            assertThat(textContent.toString()).contains("Tom", "Jerry", "XML", "safely split")
            assertThat(sawStylesheetInstruction).isTrue()
            assertThat(sawGeneratedComment).isTrue()
        }
    }

    @Test
    fun readerUtilitiesReadSkipFragmentAndCopySubtrees(): Unit {
        val source: String = """
            <root xmlns="urn:root" xmlns:p="$BOOK_NS">
              <title>Alpha <![CDATA[& Beta]]></title>
              <skip><nested>ignored</nested></skip>
              <p:copy id="c1"><p:inner>copied</p:inner></p:copy>
            </root>
        """.trimIndent()

        xmlStreaming.newGenericReader(source).use { reader: XmlReader ->
            moveToStartElement(reader, "root")
            assertThat(reader.isElement("urn:root", "root")).isTrue()

            assertThat(reader.nextTag()).isEqualTo(EventType.START_ELEMENT)
            assertThat(reader.localName).isEqualTo("title")
            assertThat(reader.readSimpleElement()).isEqualTo("Alpha & Beta")

            assertThat(reader.nextTag()).isEqualTo(EventType.START_ELEMENT)
            assertThat(reader.localName).isEqualTo("skip")
            reader.skipElement()
            assertThat(reader.eventType).isEqualTo(EventType.END_ELEMENT)
            assertThat(reader.localName).isEqualTo("skip")

            assertThat(reader.nextTag()).isEqualTo(EventType.START_ELEMENT)
            assertThat(reader.name).isEqualTo(QName(BOOK_NS, "copy", "p"))
            val fragment: CompactFragment = CompactFragment(reader.elementToFragment())

            assertThat(fragment.isEmpty).isFalse()
            assertThat(fragment.contentString)
                .contains("p:copy")
                .contains("p:inner")
                .contains("copied")

            val copiedXml: String = buildXml { writer: XmlWriter -> fragment.serialize(writer) }
            assertThat(copiedXml).contains("id=\"c1\"", "copied")
        }

        val copiedDocument: String = buildXml { writer: XmlWriter ->
            xmlStreaming.newGenericReader(source).use { reader: XmlReader ->
                writer.serialize(reader)
            }
        }
        assertThat(copiedDocument).contains("<root", "Alpha", "ignored", "copied")
    }

    @Test
    fun genericDomImplementationCreatesMutableNamespacedDocuments(): Unit {
        val document = xmlStreaming.genericDomImplementation.createDocument(STORE_NS, "s:store", null)
        val root = requireNotNull(document.documentElement)
        root.setAttributeNS(ATTR_NS, "a:currency", "EUR")

        val coffee = document.createElementNS(STORE_NS, "s:item")
        coffee.setAttribute("sku", "001")
        coffee.appendChild(document.createTextNode("Coffee"))
        root.appendChild(coffee)

        val tea = document.createElementNS(STORE_NS, "s:item")
        tea.setAttribute("sku", "002")
        tea.appendChild(document.createCDATASection("Green & Black"))
        root.appendChild(tea)

        assertThat(root.namespaceURI).isEqualTo(STORE_NS)
        assertThat(root.prefix).isEqualTo("s")
        assertThat(root.getAttributeNS(ATTR_NS, "currency")).isEqualTo("EUR")
        assertThat(root.childNodes.length).isEqualTo(2)
        assertThat(root.getElementsByTagNameNS(STORE_NS, "item").map { it.textContent })
            .containsExactly("Coffee", "Green & Black")
        assertThat(requireNotNull(coffee.parentNode).nodeName).isEqualTo("s:store")
        assertThat(requireNotNull(tea.previousSibling).textContent).isEqualTo("Coffee")

        val serialized: String = buildXml { writer: XmlWriter -> writer.serialize(document) }
        assertThat(serialized)
            .contains("s:store")
            .contains("a:currency=\"EUR\"")
            .contains("Coffee")
            .contains("Green")
            .contains("Black")
    }

    @OptIn(ExperimentalXmlUtilApi::class)
    @Test
    fun domWriterAppendsStructuredContentToExistingElement(): Unit {
        val document = xmlStreaming.genericDomImplementation.createDocument(STORE_NS, "s:store", null)
        val root = requireNotNull(document.documentElement)

        xmlStreaming.newWriter(root).use { writer: XmlWriter ->
            writer.startTag(BOOK_NS, "book", "bk")
            writer.namespaceAttr("bk", BOOK_NS)
            writer.attribute("", "id", "", "dom-1")
            writer.text("DOM ")
            writer.cdsect("content & details")
            writer.comment("available")
            writer.endTag(BOOK_NS, "book", "bk")
        }

        val book = root.getElementsByTagNameNS(BOOK_NS, "book")
            .single() as Element
        val childNodes: List<Node> = book.childNodes.toList()

        assertThat(book.namespaceURI).isEqualTo(BOOK_NS)
        assertThat(book.prefix).isEqualTo("bk")
        assertThat(book.getAttribute("id")).isEqualTo("dom-1")
        assertThat(book.getAttribute("xmlns:bk")).isEqualTo(BOOK_NS)
        assertThat(book.textContent).isEqualTo("DOM content & details")
        assertThat(requireNotNull(book.parentNode).nodeName).isEqualTo("s:store")
        assertThat(childNodes.map { it.nodetype }).containsExactly(
            NodeType.TEXT_NODE,
            NodeType.CDATA_SECTION_NODE,
            NodeType.COMMENT_NODE,
        )
        val characterData: List<String> = childNodes.map { node: Node ->
            (node as CharacterData).getData()
        }
        assertThat(characterData).containsExactly("DOM ", "content & details", "available")
    }

    @Test
    fun readerNamespaceContextResolvesDeclaredAndImplicitPrefixes(): Unit {
        val source: String = """
            <root xmlns="urn:default" xmlns:bk="$BOOK_NS" xmlns:ed="urn:edition">
              <bk:item ed:number="first" />
            </root>
        """.trimIndent()

        xmlStreaming.newGenericReader(source).use { reader: XmlReader ->
            moveToStartElement(reader, "root")
            val rootContext = reader.namespaceContext

            assertThat(rootContext.getNamespaceURI("bk")).isEqualTo(BOOK_NS)
            assertThat(rootContext.getNamespaceURI("ed")).isEqualTo("urn:edition")
            assertThat(rootContext.getPrefix(BOOK_NS)).isEqualTo("bk")
            assertThat(rootContext.getPrefixes(BOOK_NS).asSequence().toList()).containsExactly("bk")
            assertThat(reader.namespaceDecls.map { it.prefix to it.namespaceURI })
                .contains("" to "urn:default", "bk" to BOOK_NS, "ed" to "urn:edition")

            assertThat(reader.nextTag()).isEqualTo(EventType.START_ELEMENT)
            assertThat(reader.namespaceContext.getNamespaceURI("bk")).isEqualTo(BOOK_NS)
            assertThat(reader.getAttributeValue("urn:edition", "number")).isEqualTo("first")
        }
    }

    @Test
    fun bufferedReaderPeeksEventsAndPushesBackCurrentEvent(): Unit {
        val source: String = "<article><title id=\"main\">Alpha<![CDATA[ & Beta]]><!-- skipped -->" +
            " Gamma</title><empty /></article>"

        XmlBufferedReader(xmlStreaming.newGenericReader(source)).use { reader: XmlBufferedReader ->
            moveToStartElement(reader, "article")
            assertThat(reader.eventType).isEqualTo(EventType.START_ELEMENT)

            val peekedTitle: XmlEvent = requireNotNull(reader.peek())
            assertThat(peekedTitle.eventType).isEqualTo(EventType.START_ELEMENT)
            assertThat((peekedTitle as XmlEvent.StartElementEvent).localName).isEqualTo("title")
            assertThat(reader.eventType).isEqualTo(EventType.START_ELEMENT)
            assertThat(reader.localName).isEqualTo("article")

            assertThat(reader.next()).isEqualTo(EventType.START_ELEMENT)
            assertThat(reader.localName).isEqualTo("title")
            assertThat(reader.getAttributeValue("", "id")).isEqualTo("main")

            assertThat(reader.next()).isEqualTo(EventType.TEXT)
            assertThat(reader.text).isEqualTo("Alpha")
            reader.pushBackCurrent()
            assertThat(reader.next()).isEqualTo(EventType.TEXT)
            assertThat(reader.text).isEqualTo("Alpha")

            assertThat(reader.peekNextEvent()).isEqualTo(EventType.CDSECT)
            assertThat(reader.eventType).isEqualTo(EventType.TEXT)
            assertThat(reader.next()).isEqualTo(EventType.CDSECT)
            assertThat(reader.text).isEqualTo(" & Beta")
            assertThat(reader.next()).isEqualTo(EventType.COMMENT)
            assertThat(reader.text).isEqualTo(" skipped ")
            assertThat(reader.next()).isEqualTo(EventType.TEXT)
            assertThat(reader.text).isEqualTo(" Gamma")

            assertThat(reader.next()).isEqualTo(EventType.END_ELEMENT)
            assertThat(reader.localName).isEqualTo("title")
            assertThat(reader.nextTag()).isEqualTo(EventType.START_ELEMENT)
            assertThat(reader.localName).isEqualTo("empty")
        }
    }

    @Test
    fun xmlEventsCaptureReaderStateAndWriteEquivalentElementStream(): Unit {
        val source: String = "<?audit accepted?>" +
            "<events xmlns:e=\"$EVENT_NS\"><e:item id=\"42\">payload</e:item></events>"
        val events: MutableList<XmlEvent> = mutableListOf()

        xmlStreaming.newGenericReader(source).use { reader: XmlReader ->
            while (reader.hasNext()) {
                reader.next()
                events += XmlEvent.from(reader)
            }
        }

        val itemStart = events.filterIsInstance<XmlEvent.StartElementEvent>()
            .single { it.localName == "item" }
        assertThat(itemStart.namespaceUri).isEqualTo(EVENT_NS)
        assertThat(itemStart.prefix).isEqualTo("e")
        assertThat(itemStart.attributes.map { it.localName to it.value }).containsExactly("id" to "42")
        assertThat(events.filterIsInstance<XmlEvent.ProcessingInstructionEvent>().single().target)
            .isEqualTo("audit")
        assertThat(events.filterIsInstance<XmlEvent.TextEvent>().map { it.text })
            .anySatisfy { text: String -> assertThat(text).contains("payload") }

        val replayed: String = buildXml { writer: XmlWriter ->
            events
                .filterNot { it.eventType == EventType.START_DOCUMENT || it.eventType == EventType.END_DOCUMENT }
                .forEach { it.writeTo(writer) }
        }
        assertThat(replayed).contains("<events", "e:item", "id=\"42\"", "payload")
    }

    @Test
    fun domAttributeNodesCharacterDataAndChildMutationsUpdateTree(): Unit {
        val document = xmlStreaming.genericDomImplementation.createDocument(STORE_NS, "s:store", null)
        val root = requireNotNull(document.documentElement)

        val statusAttribute: Attr = document.createAttributeNS(ATTR_NS, "a:status")
        statusAttribute.value = "draft"
        assertThat(root.setAttributeNodeNS(statusAttribute)).isNull()
        assertThat(root.hasAttributeNS(ATTR_NS, "status")).isTrue()
        val statusOwner: Element = requireNotNull(requireNotNull(root.getAttributeNodeNS(ATTR_NS, "status")).ownerElement)
        assertThat(statusOwner.nodeName).isEqualTo(root.nodeName)
        assertThat(requireNotNull(root.attributes.getNamedItemNS(ATTR_NS, "status")).value).isEqualTo("draft")

        val ownerAttribute: Attr = document.createAttribute("owner")
        ownerAttribute.value = "catalog-team"
        assertThat(root.attributes.setNamedItem(ownerAttribute)).isNull()
        assertThat(requireNotNull(root.getAttributeNode("owner")).value).isEqualTo("catalog-team")
        assertThat(root.attributes.toList()).hasSize(2)

        val label = document.createElementNS(STORE_NS, "s:label")
        val labelText: CharacterData = document.createTextNode("catalog")
        labelText.insertData(0, "book ")
        labelText.appendData(" ready")
        assertThat(labelText.substringData(5, 7)).isEqualTo("catalog")
        labelText.replaceData(13, 5, "open")
        labelText.deleteData(12, 5)
        label.appendChild(labelText)
        root.appendChild(label)

        val oldItem = document.createElementNS(STORE_NS, "s:oldItem")
        val currentItem = document.createElementNS(STORE_NS, "s:currentItem")
        root.appendChild(oldItem)
        val replaced: Node = root.replaceChild(currentItem, oldItem)
        assertThat(replaced.nodeName).isEqualTo("s:oldItem")
        assertThat(replaced.parentNode).isNull()
        assertThat(requireNotNull(currentItem.parentNode).nodeName).isEqualTo(root.nodeName)

        val removedOwner: Attr = root.removeAttributeNode(ownerAttribute)
        assertThat(removedOwner.name).isEqualTo("owner")
        assertThat(root.hasAttribute("owner")).isFalse()
        assertThat(root.attributes.toList()).hasSize(1)
        assertThat(root.textContent).isEqualTo("book catalog")
        assertThat(root.childNodes.length).isEqualTo(2)
        assertThat(root.childNodes.toList().map { it.nodeName }).containsExactly("s:label", "s:currentItem")
    }

    @Test
    fun writerUtilitiesCreateAttributedContainerAndSimpleChildren(): Unit {
        val xml: String = buildXml { writer: XmlWriter ->
            writer.setPrefix("bk", BOOK_NS)
            writer.startTag(BOOK_NS, "order", "bk")
            writer.namespaceAttr("bk", BOOK_NS)
            writer.writeAttribute("id", "order-7")
            writer.writeAttribute("lineCount", 2L)
            writer.writeAttribute(QName(BOOK_NS, "category", "bk"), "fiction")
            writer.writeListIfNotEmpty(
                listOf("Alpha & Beta", "Gamma < Delta"),
                BOOK_NS,
                "lines",
                "bk",
            ) { value: String ->
                writeSimpleElement(BOOK_NS, "line", "bk", value)
            }
            writer.endTag(BOOK_NS, "order", "bk")
        }

        assertThat(xml)
            .contains("order-7")
            .contains("lineCount=\"2\"")
            .contains("Alpha &amp; Beta")
            .contains("Gamma &lt; Delta")

        xmlStreaming.newGenericReader(xml).use { reader: XmlReader ->
            moveToStartElement(reader, "order")
            assertThat(reader.name).isEqualTo(QName(BOOK_NS, "order", "bk"))
            assertThat(reader.getAttributeValue("", "id")).isEqualTo("order-7")
            assertThat(reader.getAttributeValue("", "lineCount")).isEqualTo("2")
            assertThat(reader.getAttributeValue(BOOK_NS, "category")).isEqualTo("fiction")

            assertThat(reader.nextTag()).isEqualTo(EventType.START_ELEMENT)
            assertThat(reader.name).isEqualTo(QName(BOOK_NS, "lines", "bk"))
            assertThat(reader.nextTag()).isEqualTo(EventType.START_ELEMENT)
            assertThat(reader.readSimpleElement()).isEqualTo("Alpha & Beta")
            assertThat(reader.nextTag()).isEqualTo(EventType.START_ELEMENT)
            assertThat(reader.readSimpleElement()).isEqualTo("Gamma < Delta")
            assertThat(reader.nextTag()).isEqualTo(EventType.END_ELEMENT)
            assertThat(reader.localName).isEqualTo("lines")
        }
    }

    @Test
    fun genericDomSupportsDocumentTypeFragmentsAndProcessingInstructions(): Unit {
        val implementation = xmlStreaming.genericDomImplementation
        val documentType = implementation.createDocumentType(
            "s:store",
            "-//xmlutil//Store Catalog//EN",
            "store-catalog.dtd",
        )
        val document = implementation.createDocument(STORE_NS, "s:store", null)
        val root = requireNotNull(document.documentElement)

        assertThat(documentType.name).isEqualTo("s:store")
        assertThat(documentType.publicId).isEqualTo("-//xmlutil//Store Catalog//EN")
        assertThat(documentType.systemId).isEqualTo("store-catalog.dtd")

        val instruction = document.createProcessingInstruction("review", "status=\"draft\"")
        instruction.data = "status=\"published\""
        root.appendChild(instruction)

        val fragment = document.createDocumentFragment()
        val paperback = document.createElementNS(STORE_NS, "s:item")
        paperback.setAttribute("sku", "frag-1")
        paperback.appendChild(document.createTextNode("Paperback"))
        val hardback = document.createElementNS(STORE_NS, "s:item")
        hardback.setAttribute("sku", "frag-2")
        hardback.appendChild(document.createTextNode("Hardback"))
        fragment.appendChild(paperback)
        fragment.appendChild(hardback)

        val appendedFragment = root.appendChild(fragment)
        assertThat(appendedFragment.nodetype).isEqualTo(NodeType.DOCUMENT_FRAGMENT_NODE)
        assertThat(fragment.childNodes.length).isEqualTo(0)
        assertThat(root.childNodes.toList().map { it.nodeName })
            .containsExactly("review", "s:item", "s:item")
        assertThat(instruction.target).isEqualTo("review")
        assertThat(instruction.data).isEqualTo("status=\"published\"")
        assertThat(requireNotNull(instruction.nextSibling).nodeName).isEqualTo("s:item")
        assertThat(requireNotNull(hardback.previousSibling).textContent).isEqualTo("Paperback")

        val itemText: MutableList<String> = mutableListOf()
        var sawProcessingInstruction: Boolean = false
        xmlStreaming.newReader(document).use { reader: XmlReader ->
            while (reader.hasNext()) {
                when (reader.next()) {
                    EventType.PROCESSING_INSTRUCTION -> sawProcessingInstruction = reader.piTarget == "review" &&
                        reader.piData == "status=\"published\""
                    EventType.START_ELEMENT -> if (reader.localName == "item") {
                        itemText += reader.readSimpleElement()
                    }
                    else -> Unit
                }
            }
        }

        assertThat(sawProcessingInstruction).isTrue()
        assertThat(itemText).containsExactly("Paperback", "Hardback")
    }

    private fun buildXml(block: (XmlWriter) -> Unit): String {
        val buffer = StringBuilder()
        xmlStreaming.newWriter(buffer, true, XmlDeclMode.Auto).use { writer: XmlWriter ->
            block(writer)
        }
        return buffer.toString()
    }

    private fun moveToStartElement(reader: XmlReader, localName: String): Unit {
        while (reader.hasNext()) {
            if (reader.next() == EventType.START_ELEMENT && reader.localName == localName) {
                return
            }
        }
        throw AssertionError("Did not find start element $localName")
    }

    private companion object {
        private const val BOOK_NS: String = "urn:books"
        private const val STORE_NS: String = "urn:store"
        private const val ATTR_NS: String = "urn:attributes"
        private const val EVENT_NS: String = "urn:events"
    }
}
