/*
 * This file is generated by jOOQ.
 */
package org_jooq.jooq.model.tables;


import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import org_jooq.jooq.model.College;
import org_jooq.jooq.model.Keys;
import org_jooq.jooq.model.tables.records.StudentCourseRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentCourse extends TableImpl<StudentCourseRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>college.student_course</code>
     */
    public static final StudentCourse STUDENT_COURSE = new StudentCourse();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StudentCourseRecord> getRecordType() {
        return StudentCourseRecord.class;
    }

    /**
     * The column <code>college.student_course.course_id</code>.
     */
    public final TableField<StudentCourseRecord, Long> COURSE_ID = createField(DSL.name("course_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>college.student_course.student_id</code>.
     */
    public final TableField<StudentCourseRecord, Long> STUDENT_ID = createField(DSL.name("student_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private StudentCourse(Name alias, Table<StudentCourseRecord> aliased) {
        this(alias, aliased, null);
    }

    private StudentCourse(Name alias, Table<StudentCourseRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>college.student_course</code> table reference
     */
    public StudentCourse(String alias) {
        this(DSL.name(alias), STUDENT_COURSE);
    }

    /**
     * Create an aliased <code>college.student_course</code> table reference
     */
    public StudentCourse(Name alias) {
        this(alias, STUDENT_COURSE);
    }

    /**
     * Create a <code>college.student_course</code> table reference
     */
    public StudentCourse() {
        this(DSL.name("student_course"), null);
    }

    public <O extends Record> StudentCourse(Table<O> child, ForeignKey<O, StudentCourseRecord> key) {
        super(child, key, STUDENT_COURSE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : College.COLLEGE;
    }

    @Override
    public List<ForeignKey<StudentCourseRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_STUDENT_COURSE_STUDENT_ID, Keys.FK_STUDENT_COURSE_COURSE_ID);
    }

    private transient Course _course;
    private transient Student _student;

    /**
     * Get the implicit join path to the <code>college.course</code> table.
     */
    public Course course() {
        if (_course == null)
            _course = new Course(this, Keys.FK_STUDENT_COURSE_STUDENT_ID);

        return _course;
    }

    /**
     * Get the implicit join path to the <code>college.student</code> table.
     */
    public Student student() {
        if (_student == null)
            _student = new Student(this, Keys.FK_STUDENT_COURSE_COURSE_ID);

        return _student;
    }

    @Override
    public StudentCourse as(String alias) {
        return new StudentCourse(DSL.name(alias), this);
    }

    @Override
    public StudentCourse as(Name alias) {
        return new StudentCourse(alias, this);
    }

    @Override
    public StudentCourse as(Table<?> alias) {
        return new StudentCourse(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public StudentCourse rename(String name) {
        return new StudentCourse(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public StudentCourse rename(Name name) {
        return new StudentCourse(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public StudentCourse rename(Table<?> name) {
        return new StudentCourse(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
