/*
 * Copyright and related rights waived via CC0
 *
 * You should have received a copy of the CC0 legalcode along with this
 * work. If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
 */
package io_mockk.mockk_jvm

import io.mockk.impl.instantiation.JvmAnyValueGenerator
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

public class JvmAnyValueGeneratorInnerAnyValueAnonymous2Test {
    @Test
    fun anyValueCreatesEmptyReferenceArray(): Unit {
        val generator: JvmAnyValueGenerator = JvmAnyValueGenerator(Unit)
        val arrayClass = emptyArray<GeneratedArrayElement>()::class

        val generatedValue: Any? = generator.anyValue(arrayClass, isNullable = false) {
            error("Array values must be generated by JvmAnyValueGenerator")
        }

        val generatedArray: Array<GeneratedArrayElement> = generatedValue as Array<GeneratedArrayElement>
        assertThat(generatedArray).isEmpty()
    }
}

private class GeneratedArrayElement
