/*
 * Copyright and related rights waived via CC0
 *
 * You should have received a copy of the CC0 legalcode along with this
 * work. If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
 */
package org_jooq.jooq.model.tables.records;


import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import org_jooq.jooq.model.tables.Student;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentRecord extends UpdatableRecordImpl<StudentRecord> implements Record6<Long, Integer, LocalDate, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>college.student.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>college.student.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>college.student.age</code>.
     */
    public void setAge(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>college.student.age</code>.
     */
    public Integer getAge() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>college.student.birth_date</code>.
     */
    public void setBirthDate(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>college.student.birth_date</code>.
     */
    public LocalDate getBirthDate() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>college.student.first_name</code>.
     */
    public void setFirstName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>college.student.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>college.student.gender</code>.
     */
    public void setGender(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>college.student.gender</code>.
     */
    public String getGender() {
        return (String) get(4);
    }

    /**
     * Setter for <code>college.student.last_name</code>.
     */
    public void setLastName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>college.student.last_name</code>.
     */
    public String getLastName() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Integer, LocalDate, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Integer, LocalDate, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Student.STUDENT.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Student.STUDENT.AGE;
    }

    @Override
    public Field<LocalDate> field3() {
        return Student.STUDENT.BIRTH_DATE;
    }

    @Override
    public Field<String> field4() {
        return Student.STUDENT.FIRST_NAME;
    }

    @Override
    public Field<String> field5() {
        return Student.STUDENT.GENDER;
    }

    @Override
    public Field<String> field6() {
        return Student.STUDENT.LAST_NAME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getAge();
    }

    @Override
    public LocalDate component3() {
        return getBirthDate();
    }

    @Override
    public String component4() {
        return getFirstName();
    }

    @Override
    public String component5() {
        return getGender();
    }

    @Override
    public String component6() {
        return getLastName();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getAge();
    }

    @Override
    public LocalDate value3() {
        return getBirthDate();
    }

    @Override
    public String value4() {
        return getFirstName();
    }

    @Override
    public String value5() {
        return getGender();
    }

    @Override
    public String value6() {
        return getLastName();
    }

    @Override
    public StudentRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public StudentRecord value2(Integer value) {
        setAge(value);
        return this;
    }

    @Override
    public StudentRecord value3(LocalDate value) {
        setBirthDate(value);
        return this;
    }

    @Override
    public StudentRecord value4(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public StudentRecord value5(String value) {
        setGender(value);
        return this;
    }

    @Override
    public StudentRecord value6(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public StudentRecord values(Long value1, Integer value2, LocalDate value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StudentRecord
     */
    public StudentRecord() {
        super(Student.STUDENT);
    }

    /**
     * Create a detached, initialised StudentRecord
     */
    public StudentRecord(Long id, Integer age, LocalDate birthDate, String firstName, String gender, String lastName) {
        super(Student.STUDENT);

        setId(id);
        setAge(age);
        setBirthDate(birthDate);
        setFirstName(firstName);
        setGender(gender);
        setLastName(lastName);
    }
}
