name: "Check GitHub Actions with Macaron"

on:
  pull_request:
    paths:
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  analyze:
    runs-on: "ubuntu-22.04"
    steps:
      - name: "☁️ Checkout repository"
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: "Run Macaron action"
        uses: oracle/macaron@b31acfe389133a5587d9639063ec70cb84e7bc47 # v0.23.0
        with:
          repo_path: ./
          policy_file: check-github-actions
          policy_purl: pkg:github.com/oracle/graalvm-reachability-metadata@.*
          reports_retention_days: 90
