name: "Test all metadata"

on:
  push:
    branches:
      - master
    paths:
      - '**.md'
      - 'library-and-framework-list*.json'
  workflow_dispatch:

jobs:
  build:
    name: "🧪 All metadata tests have passed"
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
