name: "Test all metadata (one version per test suite)"

on:
  workflow_dispatch:
  pull_request:
    branches:
     - master
    paths:
      - 'ci.json'
      - 'java/org/graalvm/internal/tck/MetadataFilesCheckerTask.java'

permissions:
  contents: read

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: true

jobs:
  get-all-metadata:
    if: github.event_name == 'workflow_dispatch' || github.repository == 'oracle/graalvm-reachability-metadata'
    name: "📋 Get list of all supported libraries"
    runs-on: "ubuntu-22.04"
    timeout-minutes: 5
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: "☁️ Checkout repository"
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: "🔧 Setup java"
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4
        with:
          distribution: 'graalvm'
          java-version: '21'

      - name: "🕸️ Populate matrix"
        id: set-matrix
        run: |
          ./gradlew generateMatrixBatchedCoordinates -Pbatches=16

  test-all-metadata:
    name: "🧪 ${{ matrix.coordinates }} [${{ matrix.nativeImageMode }}] (GraalVM for JDK ${{ matrix.version }} @ ${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 240
    needs: get-all-metadata
    env:
      GVM_TCK_NATIVE_IMAGE_MODE: ${{ matrix.nativeImageMode }}
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.get-all-metadata.outputs.matrix)}}
    steps:
      - name: "☁️ Checkout repository"
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: "🛠️ Setup latest native-build-tools snapshot"
        uses: ./.github/actions/setup-native-build-tools

      - name: "🔧 Setup java"
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4
        with:
          distribution: 'graalvm'
          java-version: '21'

      - name: "🔧 Download GraalVM for metadata testing"
        uses: graalvm/setup-graalvm@60c26726de13f8b90771df4bc1641a52a3159994 # v1
        with:
          distribution: 'graalvm'
          java-version: ${{ matrix.version }}
          set-java-home: 'false'
          native-image-job-reports: 'true'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Pull allowed docker images"
        run: |
          ./gradlew pullAllowedDockerImages -Pcoordinates=${{ matrix.coordinates }}

      - name: "Disable docker networking"
        run: bash ./.github/workflows/scripts/disable-docker.sh

      - name: "🧪 Run '${{ matrix.coordinates }}' tests"
        run: |
          ./gradlew test -Pcoordinates=${{ matrix.coordinates }}

  all-metadata-passed:
    name: "🧪 All metadata tests have passed"
    runs-on: "ubuntu-22.04"
    timeout-minutes: 1
    needs: test-all-metadata
    steps:
      - name: "All tests passed"
        if: needs.test-all-metadata.result == 'success'
        run: exit 0

      - name: "Some tests failed"
        if: needs.test-all-metadata.result == 'failure'
        run: exit 1
